---
permalink: windows/concept-accessing-snapmanager.html 
sidebar: sidebar 
keywords: access, snapmanager, command-line, interface, cli, graphical, user, interface, gui 
summary: 'Es posible acceder a SnapManager por medio de la interfaz de línea de comandos (CLI) o de la interfaz gráfica de usuario (GUI).' 
---
= Acceso a SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible acceder a SnapManager por medio de la interfaz de línea de comandos (CLI) o de la interfaz gráfica de usuario (GUI).

Es posible realizar operaciones de SnapManager distintas de las siguientes maneras:

* Si se introducen comandos en la CLI en un host que está en la misma red que el host de la base de datos.
+
Para obtener una lista de todos los comandos y una explicación de sus opciones y argumentos, consulte el capítulo referencia de comandos.

+
Para acceder a la CLI, haga clic en *Inicio* > *todos los programas* > *NetApp* > *SnapManager para SAP* > *Iniciar interfaz de línea de comandos SMSAP (CLI)*.

* Mediante el acceso a la GUI en un host en la misma red que el host de la base de datos.
+
La interfaz gráfica de usuario proporciona sencillos asistentes que ayudan a realizar diferentes operaciones.

* Mediante los comandos SAP BR*Tools.

