---
permalink: windows/concept-general-layout-and-configuration.html 
sidebar: sidebar 
keywords: information, recommend, general, database, layout, storage, configuration, issue, disk, group, file, type, tablespace 
summary: Se puede encontrar información acerca de la distribución general de la base de datos y las configuraciones de almacenamiento recomendadas para evitar problemas relacionados con los grupos de discos, los tipos de archivo y los espacios de tablas. 
---
= Diseño y configuración generales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se puede encontrar información acerca de la distribución general de la base de datos y las configuraciones de almacenamiento recomendadas para evitar problemas relacionados con los grupos de discos, los tipos de archivo y los espacios de tablas.

* No incluya archivos de más de un tipo DE sistema DE archivos SAN en la base de datos.
+
Todos los archivos que conforman una base de datos deben residir en el mismo tipo de sistema de archivos.

* SnapManager requiere un gran tamaño de bloque de 4 KB.


A continuación se muestran algunas directrices para la separación de volúmenes:

* Los archivos de datos de una sola base de datos deben estar en el volumen.
* Debe utilizar volúmenes independientes para cada una de las siguientes clasificaciones de archivos: Archivos binarios de base de datos, archivos de datos, archivos redo log en línea, archivos redo log archivados y archivos de control.
* No es necesario crear un volumen separado para los archivos de base de datos temporales, ya que SnapManager no realiza backups de archivos de base de datos temporales.


SAP utiliza un diseño estándar para instalaciones de bases de datos Oracle. En este diseño, SAP coloca copias del archivo de control de Oracle en `E:\oracle\SID\origlogA, E:\oracle\SID\origlogB, and E:\oracle\SID\sapdata1 file systems`.


NOTE: Debido a que los backups BR*Tools incluyen los perfiles Oracle y SAP ubicados en el subdirectorio de la base de datos de la instalación de Oracle, la instalación de Oracle debe estar ubicada en el almacenamiento.

En el caso de una nueva instalación, puede modificar la ubicación de los archivos de control utilizando SAPINST y mover el archivo de control normalmente colocado en el sistema de archivos sapdata1 a un sistema de archivos que no reside en el mismo volumen que los archivos de datos. (SAPINST es la herramienta que proporciona SAP para la instalación de sistemas SAP.)

Para obtener más información, consulte el _SnapManager for SAP Best Practices_.

*Información relacionada*

http://media.netapp.com/documents/tr-3823.pdf["Prácticas recomendadas de SnapManager para SAP: media.netapp.com/documents/tr-3823.pdf"^]
