---
permalink: windows/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, user, allow, resource, repository, repositories, host, profile, credential, management 
summary: Puede gestionar la seguridad en SnapManager aplicando autenticación de usuario. El método de autenticación de usuario permite acceder a recursos como repositorios, hosts y perfiles. 
---
= Seguridad y gestión de credenciales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede gestionar la seguridad en SnapManager aplicando autenticación de usuario. El método de autenticación de usuario permite acceder a recursos como repositorios, hosts y perfiles.

Cuando se realiza una operación mediante la interfaz de línea de comandos (CLI) o la interfaz gráfica de usuario (GUI), SnapManager recupera las credenciales establecidas para repositorios y perfiles. SnapManager guarda las credenciales de instalaciones anteriores.

El repositorio y los perfiles se pueden proteger con una contraseña. Una credencial es la contraseña configurada para el usuario de un objeto y la contraseña no está configurada en el objeto en sí.

Puede gestionar la autenticación y las credenciales realizando las siguientes tareas:

* Gestione la autenticación de usuario mediante solicitudes de contraseña en las operaciones o mediante el `smsap credential set` comando.
+
Configurar credenciales para un repositorio, host o perfil.

* Vea las credenciales que rigen los recursos a los que tiene acceso.
* Borre las credenciales de un usuario para todos los recursos (hosts, repositorios y perfiles).
* Eliminar credenciales de un usuario para recursos individuales (hosts, repositorios y perfiles).



NOTE: Si la base de datos del repositorio está en un host de Windows, tanto el usuario local como el administrador y el usuario de dominio deben tener las mismas credenciales.
