---
permalink: windows/reference-the-smosmsapoperation-list-command.html 
sidebar: sidebar 
keywords: command, list, summary, information, operation, record, profile, smsap 
summary: Este comando muestra la información resumida de todas las operaciones registradas en un perfil especificado. 
---
= El comando smsap operation list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando muestra la información resumida de todas las operaciones registradas en un perfil especificado.



== Sintaxis

[listing]
----

smsap operation list
-profile profile_name
[-delimiter character]
[-quiet | -verbose]
----


== Parámetros

* *`-profile _profile_name_`*
+
Especifica el nombre del perfil. Este nombre puede tener hasta 30 caracteres y debe ser único dentro del host.

* *`-delimiter _character_`*
+
(Opcional) cuando se especifica este parámetro, el comando enumera cada fila en una línea independiente y los atributos de esa fila están separados por el carácter especificado.

* *`-quiet`*
+
(Opcional) sólo muestra mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *`-verbose`*
+
(Opcional) muestra mensajes de error, advertencia e informativos en la consola.





== Comando de ejemplo

En el siguiente ejemplo, se muestra la información de resumen de todas las operaciones registradas con el perfil especificado.

[listing]
----
smsap operation list -profile myprofile
----
[listing]
----
Start Date Status Operation ID Type Host
-------------------- ---------- -------------------------------- ------------------ --
2007-07-16 16:03:57 SUCCESS 8abc01c813d0a1530113d0a15c5f0005 Profile Create Host3
2007-07-16 16:04:55 FAILED 8abc01c813d0a2370113d0a241230001 Backup Host3
2007-07-16 16:50:56 SUCCESS 8abc01c813d0cc580113d0cc60ad0001 Profile Update Host3
2007-07-30 15:44:30 SUCCESS 8abc01c81418a88e011418a8973e0001 Remove Backup Host3
2007-08-10 14:31:27 SUCCESS 8abc01c814510ba20114510bac320001 Backup Host3
2007-08-10 14:34:43 SUCCESS 8abc01c814510e9f0114510ea98f0001 Mount Host3
2007-08-10 14:51:59 SUCCESS 8abc01c814511e6e0114511e78d40001 Unmount Host3
----