---
permalink: windows/reference-the-smosmsap-repository-rollingback-command.html 
sidebar: sidebar 
keywords: command, enable, roll, back, revert, version, snapmanager, upgrade, smsap 
summary: Este comando permite revertir o revertir una versión superior de SnapManager a la versión original de la que se actualizó. 
---
= El comando smsap repository
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando permite revertir o revertir una versión superior de SnapManager a la versión original de la que se actualizó.



== Sintaxis

[listing]
----

smsap repository rollback
-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port
-rollbackhost host_with_target_database
[-force]
[-quiet | -verbose]
----


== Parámetros

* *`-repository`*
+
Las opciones siguientes `-repository` especifique los detalles de la base de datos para el repositorio.

* *`-dbname _repo_service_name_`*
+
Especifica el nombre de la base de datos que almacena el repositorio. Utilice el nombre global o el SID.

* *`-host _repo_host_`*
+
Especifica el nombre o la dirección IP del equipo host en el que se ejecuta la base de datos del repositorio.

* *`-login`*
+
Inicia los detalles de inicio de sesión en el repositorio.

* *`-username _repo_username_`*
+
Especifica el nombre de usuario necesario para acceder a la base de datos que almacena el repositorio.

* *`-rollbackhost _host_with_target_database_`*
+
Especifica el nombre del host que se va a revertir de una versión superior de SnapManager a la versión anterior original.

* *`-port _repo_port_`*
+
Especifica el número de puerto TCP utilizado para acceder a la base de datos que almacena el repositorio.

* *`-force`*
+
Intenta forzar la actualización del repositorio. SnapManager le solicita que realice una copia de seguridad del repositorio actual antes de la actualización.

* *`-noprompt`*
+
No muestra el mensaje antes de actualizar la base de datos del repositorio. Con el `-noprompt` la opción garantiza que no aparezca el mensaje, lo que facilita la actualización de repositorios mediante una secuencia de comandos.

* *`-quiet`*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *`-verbose`*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Comando de ejemplo

En el ejemplo siguiente se actualiza el repositorio de la base de datos SALESDB.

[listing]
----
smsap repository rollback -repository -dbname SALESDB
-host server1 -login -username admin -port 1521 -rollbackhost hostA
----