---
permalink: windows/reference-the-smosmsap-clone-update-command.html 
sidebar: sidebar 
keywords: command, update, information, clone, comment, smsap 
summary: Este comando actualiza información acerca del clon. Puede actualizar el comentario. 
---
= El comando smsap clone update
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando actualiza información acerca del clon. Puede actualizar el comentario.



== Sintaxis

[listing]
----

smsap clone update
-profile profile_name
[-label label | -id id]
-comment  commment_text
[-quiet | -verbose]
----


== Parámetros

* *`-profile _profile_name_`*
+
Especifica el nombre del perfil que contiene el clon que desea actualizar. El perfil contiene el identificador de la base de datos y otra información de la base de datos.

* *`-id _id_`*
+
Especifica el ID del clon. SnapManager genera el ID cuando crea un clon. Utilice la `smsap clone list` Comando para mostrar el ID de cada clon.

* *`-label _label_`*
+
Especifica la etiqueta del clon.

* *`-comment`*
+
Muestra el comentario introducido en la creación del clon. Este es un parámetro opcional.

* *`-quiet`*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *`-verbose`*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Comando de ejemplo

En el siguiente ejemplo se actualiza el comentario del clon.

[listing]
----
smsap clone update -profile anson.pcrac5
-label clone_pcrac51_20080820141624EDT  -comment See updated clone
----