---
permalink: windows/reference-the-smosmsapbackup-unmount-command.html 
sidebar: sidebar 
keywords: run, backup, unmount, command, smsap 
summary: Puede ejecutar el comando backup umount para desmontar un backup. 
---
= El comando smsap backup unmount
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar el `backup unmount` comando para desmontar un backup.



== Sintaxis

[listing]
----

smsap backup unmount
-profile profile_name
[-label label [-data | -archivelogs] | [-id id]
[-force]
[-dump]
[-quiet | -verbose]
----


== Parámetros

* *`-profile _profile_name_`*
+
Especifica el perfil para el que desea desmontar un backup. El perfil contiene el identificador de la base de datos y otra información de la base de datos.

* *`-id _id_`*
+
Desmonta el backup con el GUID especificado. SnapManager genera el GUID cuando se crea un backup. Puede utilizar el `smsap backup list` Comando para mostrar el GUID de cada backup.

* *`-label _label_`*
+
Desmonta el backup con la etiqueta especificada.

* *`-data`*
+
Especifica los archivos de datos.

* *`-archivelogs`*
+
Especifica los archivos de registro de archivos.

* *`-dump`*
+
Recoge los archivos de volcado después de una operación de desmontaje correcta o con errores.

* *`-force`*
+
Desmonta el backup incluso si hay problemas en la liberación de los recursos asociados con el backup. SnapManager intenta desmontar el backup y borrar todos los recursos asociados. El registro muestra la operación de desmontaje correcta, pero es posible que deba limpiar los recursos de forma manual si hay errores en el registro.

* *`-quiet`*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *`-verbose`*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Ejemplo

A continuación se muestra un ejemplo de una operación de desmontaje:

[listing]
----
# smsap backup unmount -label test -profile SALES1 -verbose
----
[listing]
----
[INFO ]: SMSAP-13051: Process PID=9788
[INFO ]: SMSAP-13036: Starting operation Backup Unmount on host hadley.domain.private
[INFO ]: SMSAP-13036: Starting operation Backup Unmount on host hadley.domain.private
[INFO ]: SMSAP-13046: Operation GUID 8abc015738849a3d0138849a43900001 starting on Profile FAS_P1
[INFO ]: SD-00031: Beginning to disconnect filesystem(s) [C:\SnapManager_auto_mounts\H-2012071400592312_0, C:\SnapManager_auto_mounts\I-2012071400592328_0].
[INFO ]: SD-00032: Finished disconnecting filesystem(s) [C:\SnapManager_auto_mounts\H-2012071400592312_0, C:\SnapManager_auto_mounts\I-2012071400592328_0].
[INFO ]: SMSAP-13048: Backup Unmount Operation Status: SUCCESS
[INFO ]: SMSAP-13049: Elapsed Time: 0:07:26.754
----