---
permalink: windows/reference-the-smosmsap-history-remove-command.html 
sidebar: sidebar 
keywords: command, enable, remove, history, snapmanager, operation, associate, single, profile, multiple, repository, smsap 
summary: Este comando permite quitar el historial de operaciones de SnapManager asociadas con un único perfil, varios perfiles o todos los perfiles bajo un repositorio. 
---
= Comando smsap history remove
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando permite quitar el historial de operaciones de SnapManager asociadas con un único perfil, varios perfiles o todos los perfiles bajo un repositorio.



== Sintaxis

[listing]
----

smsap history remove
-profile {-name profile_name [profile_name1, profile_name2] | -all
-repository
-login [-password repo_password]
-username repo_username
-host repo_host
-dbname repo_dbname
-port repo_port}
-operation {-operations operation_name [operation_name, operation_name2] | -all}
[-quiet | -verbose]
----


== Parámetros

* *`-profile _profile_`*
+
Especifica el nombre del perfil. Este nombre puede tener hasta 30 caracteres y debe ser único dentro del host.

* *`-repository`*
+
Las opciones que siguen -repository especifican los detalles de la base de datos que almacena el perfil.

* *`-dbname _repo_dbname_`*
+
Especifica el nombre de la base de datos que almacena el perfil. Utilice el nombre global o el SID.

* *`-host _repo_host_`*
+
Especifica el nombre o la dirección IP del equipo host en el que se ejecuta la base de datos del repositorio.

* *`-login`*
+
Inicia los detalles de inicio de sesión en el repositorio.

* *`-username _repo_username_`*
+
Especifica el nombre de usuario necesario para acceder a la base de datos que almacena el repositorio.

* *`-port _repo_port_`*
+
Especifica el número de puerto TCP utilizado para acceder a la base de datos que almacena el repositorio.

* *`-operation {-operations operation_name [operation_name1, operation_name2] | -all`*
+
Especifica la operación SnapManager para la que se configura el historial.

* *`-quiet`*
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* *`-verbose`*
+
Muestra mensajes de error, advertencia e informativos en la consola.





== Comando de ejemplo

[listing]
----
smsap history purge -profile -name PROFILE1 -operation -operations backup
-verbose
----