---
permalink: windows/task-creating-profiles.html 
sidebar: sidebar 
keywords: creating, create, profile, assign, oracle, database, policy, set, retention, count, class 
summary: Al crear perfiles, puede asignar una cuenta de usuario de base de datos Oracle concreta al perfil. Puede establecer la política de retención para el perfil y establecer el recuento de retención y la duración de cada clase de retención. 
---
= Creación de perfiles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al crear perfiles, puede asignar una cuenta de usuario de base de datos Oracle concreta al perfil. Puede establecer la política de retención para el perfil y establecer el recuento de retención y la duración de cada clase de retención.

Si no se proporcionan los valores de los parámetros -login, -password y -Port de la base de datos, el modo de autenticación del sistema operativo utiliza las credenciales predeterminadas.

Al crear un perfil, SnapManager realiza una comprobación de elegibilidad de restauración para determinar el mecanismo de restauración que puede usarse para restaurar la base de datos.

SnapManager (3.2 o posterior) permite separar los archivos de registro de archivos de los archivos de datos al crear un nuevo perfil o actualizar un perfil existente. Después de separar el backup con el perfil, se puede crear únicamente el backup de los archivos de datos o el backup de solo registro del archivo de la base de datos. Se puede usar el nuevo perfil o el perfil actualizado para crear el backup que contiene tanto los archivos de datos como los archivos de registro de archivos. Sin embargo, no se puede utilizar el perfil para crear el backup completo ni revertir la configuración.

*Perfiles para crear copias de seguridad completas y parciales*

Es posible crear perfiles para crear un backup completo de la base de datos que contenga los archivos de datos, los archivos de control, los archivos de registro de archivos y el backup parcial de la base de datos que contenga los archivos de datos o espacios de tablas especificados, todos los archivos de control y todos los archivos de registro de archivos. SnapManager no permite crear backups de registros de archivos independientes con los perfiles creados para backups completos y parciales.

*Perfiles para la creación de copias de seguridad sólo de archivos de datos y copias de seguridad sólo archivogs*

Al crear un nuevo perfil, puede incluir -separate-archivvelog-backups para separar el backup del registro de archivo del backup del archivo de datos. También puede actualizar el perfil existente para separar la copia de seguridad del archivo de datos.

Al usar las opciones nuevas de perfil para separar los backups de los registros de archivos, es posible realizar las siguientes operaciones de SnapManager:

* Cree un backup de registro de archivos
* Eliminar un backup de registro de archivos
* Montar un backup de registro de archivos
* Liberar un backup de registro de archivo


Al crear el perfil para separar los backups de registros de archivos del backup de archivos de datos, si los archivos de registro de archivos no existen en la base de datos para la que se creó el perfil, no existe un archivo de registro archivado con mensaje de advertencia en el sistema de archivos activo. Las versiones del archivo de registro archivado anteriores al archivo de registro de <archive log thread version> no se incluirán en el backup. Incluso si se crean backups para esta base de datos, los archivos de registro de archivos no están disponibles en los backups de la base de datos.


NOTE: Si se produce un error al crear un perfil, utilice el comando smsapsystem dump. Después de crear un perfil, si encuentra un error, utilice los comandos dump ssssssapoperation y dump ssssapprofile.

. Para crear un perfil con un nombre de usuario, una contraseña y un puerto (autenticación de Oracle), introduzca el comando siguiente:
+
`smsap profile create -profileprofile [-profile-passwordprofile_password] -repository-dbnamerepo_dbname-hostrepo_host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port] [-rman {-controlfile | {-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname} } ] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][-summary-notification] [-notification [-success-emailemail_address1, email_address2-subjectsubject_pattern] [-failure-emailemail_address1, email_address2-subjectsubject_pattern]][-separate-archivelog-backups-retain-archivelog-backups-hourshours | -daysdays | -weeksweeks| -monthsmonths [-include-with-online-backups | -no-include-with-online-backups]] [-dump]`

+
Las demás opciones para este comando son las siguientes:

+
[-force] [-noprompt]

+
También puede incluir otras opciones al crear perfiles, dependiendo de cómo desee tener acceso a la base de datos.

+
|===
| Si... | Realice lo siguiente... 


 a| 
*Desea utilizar la autenticación de base de datos para crear un perfil*
 a| 
Especifique los detalles de inicio de sesión de la base de datos.



 a| 
*Desea especificar una política de retención de copias de seguridad para copias de seguridad*
 a| 
Especifique el recuento de retención o la duración de una clase de retención, o ambos. La duración se encuentra en unidades de la clase (por ejemplo, horas por hora, días por día).

** -hourly es la clase de retención por hora, para la cual [-count n] [-duration m] son el recuento de retención y la duración de la retención, respectivamente.
** -daily es la clase de retención diaria, para la cual [-count n] [-durationm] son el recuento de retención y la duración de la retención, respectivamente.
** -weekly es la clase de retención semanal, para la cual [-count n] [-duration m] son el recuento de retención y la duración de la retención, respectivamente.
** -monthly es la clase de retención mensual, para la cual [-count n] [-durationm] son el recuento de retención y la duración de la retención, respectivamente.




 a| 
*Desea activar la notificación por correo electrónico para el estado de finalización de las operaciones de la base de datos*
 a| 
Especifique las siguientes opciones y variables:

** -summary-notification permite configurar una notificación de correo electrónico de resumen para varios perfiles en una base de datos de repositorio.
** -notification permite recibir una notificación por correo electrónico del estado de finalización de la operación de base de datos de un perfil.
** -success-emailemail_address2 le permite recibir una notificación por correo electrónico sobre la operación correcta de la base de datos mediante un perfil nuevo o existente.
** -failure-emailemail_address2 le permite recibir una notificación por correo electrónico sobre la operación de la base de datos fallida realizada mediante un perfil nuevo o existente.
** -subjectsubject_text especifica el texto del asunto para la notificación de correo electrónico al crear un perfil nuevo o uno existente. Si los ajustes de notificación no están configurados para el repositorio e intenta configurar las notificaciones de perfil o resumen mediante la CLI, se registra el siguiente mensaje en el registro de consola: SMSAP-14577: Notification Settings no configurado.
+
Si ha configurado la configuración de notificación e intenta configurar la notificación de resumen utilizando la CLI sin habilitar la notificación de resumen para el repositorio, el siguiente mensaje se muestra en el registro de consola: __**__SMSAP-14575: La configuración de notificación de resumen no está disponible para este repositorio





 a| 
*Desea hacer una copia de seguridad de los archivos de registro de archivos por separado de los archivos de datos*
 a| 
Especifique las siguientes opciones y variables:

** -separar-archivvelog-backups permite separar el backup de registros de archivo del backup del archivo de datos.
** -retain-archivvelog-backups establece la duración de la retención para los backups de registros de archivos. Debe especificar una duración de retención positiva.
+
Los backups de los registros de archivos se conservan según la duración de retención de los registros de archivo. Los backups de los archivos de datos se retienen en función de las políticas de retención existentes.

** -include-with-online-backups incluye el backup de registros de archivos junto con el backup de base de datos en línea.
+
Esta opción permite crear un backup de archivos de datos en línea y un backup de registros de archivos juntos para el clonado. Cuando se configura esta opción, siempre que se crea un backup de archivos de datos en línea, se crean los backups de los registros de archivos junto con los archivos de datos inmediatamente.

** -no-include-with-online-backups no incluye el backup de registros de archivo junto con el backup de base de datos.




 a| 
*Puede recopilar los archivos de volcado después de que la operación de creación de perfil se haya realizado correctamente*
 a| 
Especifique la opción -dump al final del comando profile create.

|===


*Información relacionada*

xref:concept-how-to-collect-dump-files.adoc[Cómo recopilar archivos de volcado]
