---
permalink: windows/task-updating-profiles.html 
sidebar: sidebar 
keywords: update, profile, modify, password, backup, database, operating, system, authentication, information, host, oracle, updating 
summary: 'Puede actualizar los perfiles para modificar la contraseña del perfil, el número de backups a retener, el acceso a la base de datos, la autenticación del sistema operativo \(OS\) a la autenticación de la base de datos y viceversa, así como la información sobre el host. Si cambia la información de contraseña de la base de datos Oracle, también debe cambiar esa información en el perfil.' 
---
= Actualizando perfiles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede actualizar los perfiles para modificar la contraseña del perfil, la cantidad de backups que se deben retener, el acceso a la base de datos, la autenticación del sistema operativo (SO) con la autenticación de la base de datos y viceversa, e información sobre el host. Si cambia la información de contraseña de la base de datos Oracle, también debe cambiar esa información en el perfil.

SnapManager (3.2 o posterior) permite actualizar el perfil para separar los backups de registros de archivos de los backups de archivos de datos con la opción -separate-archivvelog-backups. Es posible especificar una duración de retención separada para el backup del registro de archivo. SnapManager le permite incluir el backup de registros de archivos junto con el backup de base de datos en línea. También puede crear un backup de archivo de datos en línea y un backup de registro de archivo juntos para clonar. Cuando se crea un backup de archivos de datos en línea, los backups de registros de archivos se crean inmediatamente junto con los archivos de datos.

.Paso
. Introduzca el siguiente comando:
+
`smsap profile update -profileprofile [-new-profilenew_profile_name] [-profile-passwordprofile_password][-database-dbnamedb_dbname-host db_host [-siddb_sid] [-login -usernamedb_username-password db_password-port db_port]] [{-rman{-controlfile | {-login  -usernamerman_username-password  rman_password-tnsname  rman_tnsname}}} | -remove-rman] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern] [-summary-notification] [-notification [-success-emailemail_address1, email_address2-subjectsubject_pattern] [-failure-emailemail_address1, email_address2-subjectsubject_pattern]] [-separate-archivelog-backups-retain-archivelog-backups-hourshours | -daysdays | -weeksweeks| -monthsmonths [-include-with-online-backups | -no-include-with-online-backups]] [-dump]`

+
Las demás opciones para este comando son las siguientes:

+
[-force] [-noprompt]

+
|===
| Si desea... | Realice lo siguiente... 


 a| 
*Cambiar la política de retención de copias de seguridad para copias de seguridad de la base de datos en el perfil*
 a| 
Especifique el recuento de retención o la duración de la retención para una clase de retención, o ambos, para cambiar la política de retención. La duración se encuentra en unidades de la clase (por ejemplo, horas por hora, días por día).

** -hourly es la clase de retención por hora, para la que [-compensn] [-durationm]] son el recuento de retención y la duración de la retención, respectivamente.
** -daily es la clase de retención diaria, para la cual [-compensn] [-durationm]] son el recuento de retención y la duración de la retención, respectivamente.
** -weekly es la clase de retención semanal, para la cual [-compensn] [-durationm]] son el recuento de retención y la duración de la retención, respectivamente.
** -mensual es la clase de retención mensual, para la que [-compensn] [-durationm]] son el recuento de retención y la duración de la retención, respectivamente.




 a| 
*Activar notificaciones por correo electrónico para el estado de finalización de las operaciones de la base de datos*
 a| 
Especifique las siguientes opciones y variables:

** -summary-notification permite configurar una notificación de correo electrónico de resumen para varios perfiles en una base de datos de repositorio.
** -notification permite recibir una notificación por correo electrónico sobre el estado de finalización de la operación de base de datos de un perfil.
** -success-emailemail_dirección2 le permite recibir una notificación por correo electrónico tras la finalización de una operación de base de datos exitosa usando un perfil nuevo o existente.
** -failure-emailemail_address2 le permite recibir una notificación por correo electrónico en una operación de base de datos fallida realizada mediante un perfil nuevo o existente.
** -subjectsubject_text especifica el texto del asunto para la notificación de correo electrónico mientras se crea un perfil nuevo o un perfil existente. Si los ajustes de notificación no están configurados para el repositorio y está intentando configurar notificaciones de perfil o resumen mediante la interfaz de línea de comandos (CLI), se registra el siguiente mensaje en el registro de consola: SMSAP-14577: Ajustes de notificación no configurados.
+
Si ha configurado la configuración de notificación y está intentando configurar la notificación de resumen utilizando la CLI sin habilitar la notificación de resumen para el repositorio, el siguiente mensaje se registra en el registro de consola: __**__SMSAP-14575: La configuración de notificación de resumen no está disponible para este repositorio





 a| 
*Actualice el perfil para crear una copia de seguridad de los archivos de registro de archivos por separado*
 a| 
Especifique las siguientes opciones y variables:

** -separate-archivvelog-backups permite crear una copia de seguridad de los archivos de registro de archivos por separado de los archivos de la base de datos.
+
Después de especificar esta opción, puede crear una copia de seguridad sólo de archivos de datos o una copia de seguridad sólo de archivvelogs. No es posible crear un backup completo. Además, no puede revertir la configuración del perfil separando la copia de seguridad. SnapManager conserva los backups según la política de retención de los backups que se crearon antes de usar un backup de solo archivado.

** -retain-archivvelog-backups establece la duración de la retención para los backups de registros de archivos.
+

NOTE: Si actualiza el perfil por primera vez, puede separar los backups de registros de archivos del backup de archivos de datos con la opción -separate-archivvelog-backups; debe proporcionar la duración de retención para los backups de registros de archivos mediante la opción -retain-archivvelog-backups. La configuración de la duración de la retención es opcional cuando se actualiza el perfil más adelante.

** -include-with-online-backups especifica que el backup de registros de archivos se incluye junto con el backup de base de datos.
** -no-include-with-online-backups especifica el backup del archivo de registro de archivos no se incluye junto con el backup de base de datos.




 a| 
*Cambiar el nombre de host de la base de datos de destino*
 a| 
Especifique -hostnew_dB_host para cambiar el nombre de host del perfil.



 a| 
*Recopilar los archivos de volcado después de la operación de actualización de perfil*
 a| 
Especifique la opción -dump.

|===
. Para ver el perfil actualizado, escriba el siguiente comando: SmSAP profile show


*Información relacionada*

xref:concept-how-to-collect-dump-files.adoc[Cómo recopilar archivos de volcado]
