---
permalink: windows/task-mount-backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, handle, mount, backup, host, available, scenario, tools, oracle, recovery, manager, rman, file 
summary: 'SnapManager se encarga automáticamente del montaje de un backup para que el host esté disponible. También es posible montar backups en situaciones en las que se utilice una herramienta externa, como Oracle Recovery Manager (RMAN), para acceder a los archivos de la copia de seguridad.' 
---
= Montar backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager se encarga automáticamente del montaje de un backup para que el host esté disponible. También es posible montar backups en situaciones en las que se utilice una herramienta externa, como Oracle Recovery Manager (RMAN), para acceder a los archivos de la copia de seguridad.



== Acerca de esta tarea

La `smsap backup mount` Comando muestra una lista de las rutas en las que se han montado las copias Snapshot que constan del backup.


NOTE: Opcionalmente, es posible recoger los archivos de volcado después de una operación de montaje de backup exitosa o con errores.

.Paso
. Para montar un backup, introduzca el siguiente comando:
+
`*smsap backup mount -profile _profile_name_ _label_ [data | -archivelogs] | -id _id_} [-host _-host_] [-dump] [-quiet | -verbose]*`


