---
permalink: windows/task-unmounting-backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, unmount, backup, available, external, tool, oracle, recovery, manager, rman, file, remove, access 
summary: 'SnapManager desmonta automáticamente el backup para que no esté disponible para el servidor host. SnapManager también le permite desmontar si utiliza una herramienta externa, como Oracle Recovery Manager \(RMAN\), para acceder a los archivos de la copia de seguridad y para cambiar el estado de la copia de seguridad para eliminar el acceso.' 
---
= Desmontaje de backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager desmonta automáticamente el backup para que no esté disponible para el servidor host. SnapManager también permite desmontar si se utiliza una herramienta externa, como Oracle Recovery Manager (RMAN), para acceder a los archivos de la copia de seguridad y para cambiar el estado del backup para quitar el acceso.

Otra opción es recoger los archivos de volcado después de una operación de backup realizó una operación de desmontaje correcta o con errores.

.Paso
. Introduzca el siguiente comando:
+
`smsap backup unmount -profile profile_name {labellabel [data | -archivelogs] | -idid} [-quiet | -verbose]`



*Información relacionada*

xref:reference-the-smosmsapbackup-unmount-command.adoc[El comando smsap backup unmount]
