---
permalink: windows/task-mounting-backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, handle, mount, backup, host, available, scenario, tools, oracle, recovery, manager, rman, file 
summary: 'SnapManager se encarga automáticamente del montaje de un backup para que el host esté disponible. También puede montar copias de seguridad en situaciones en las que utilice una herramienta externa, como Oracle Recovery Manager \(RMAN\), para acceder a los archivos de la copia de seguridad.' 
---
= Montar backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager se encarga automáticamente del montaje de un backup para que el host esté disponible. También es posible montar backups en situaciones en las que se utilice una herramienta externa, como Oracle Recovery Manager (RMAN), para acceder a los archivos de la copia de seguridad.

El comando smsap backup Mount muestra una lista de las rutas en las que se han montado las copias Snapshot compuestas por el backup.


NOTE: Opcionalmente, es posible recoger los archivos de volcado después de una operación de montaje de backup exitosa o con errores.

. Para montar un backup, introduzca el siguiente comando:
+
`smsap backup mount -profile profile_name label [data | -archivelogs] | -id id} [-host-host] [-dump] [-quiet | -verbose]`



*Información relacionada*

xref:reference-the-smosmsapbackup-mount-command.adoc[El comando smsap backup Mount]
