---
permalink: windows/task-adding-new-profile-to-summary-notification.html 
sidebar: sidebar 
keywords: configure, summary, email, notification, repository, database, profile, command, add 
summary: Después de configurar una notificación por correo electrónico de resumen para la base de datos de repositorio, puede agregar un nuevo perfil a la notificación de resumen utilizando el comando summary notification. 
---
= Adición de un nuevo perfil para resumir las notificaciones por correo electrónico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de configurar una notificación por correo electrónico de resumen para la base de datos de repositorio, puede agregar un nuevo perfil a la notificación de resumen utilizando el comando summary notification.

. Introduzca el siguiente comando: `smsap profile create -profileprofile_name [-profile-passwordprofile_password] -repository-dbnamerepo_service_name-hostrepo_host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port] [-rman {-controlfile | \{-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname} } ] [-retain [-hourly-countn] [-durationm]] [-daily-countn] [-durationm]] [-weekly-countn] [-durationm]] [-monthly-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][ [ ]] [-summary-notification]`
+
Las demás opciones para este comando son las siguientes:

+
[-fuerza]


