---
permalink: windows/task-customizing-e-mail-subject-for-a-new-profile.html 
sidebar: sidebar 
keywords: customize, email, subject, profile, create, cusomtizing 
summary: Puede personalizar el asunto del correo electrónico para el nuevo perfil cuando lo cree. 
---
= Personalización del asunto del correo electrónico para un nuevo perfil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede personalizar el asunto del correo electrónico para el nuevo perfil cuando lo cree.

Puede personalizar el asunto del correo electrónico utilizando el patrón \{profile}_\{operation-name}_\{dB-sid}_\{dB-host}_\{start-date}_\{end-date}_\{status} o bien introducir su propio texto.

|===
| Nombre de la variable | Descripción | Valor de ejemplo 


 a| 
perfil
 a| 
Nombre de perfil utilizado para la operación de base de datos
 a| 
PROF1



 a| 
nombre-operación
 a| 
Nombre de la operación de base de datos
 a| 
Backup, copia de seguridad de datos, copia de seguridad de registros de datos y archivos



 a| 
db-sid
 a| 
SID de la base de datos
 a| 
DB1



 a| 
host de base de datos
 a| 
Nombre del servidor host
 a| 
Hosta



 a| 
fecha de inicio
 a| 
La hora de inicio de la operación de la base de datos en el formato mdd:hh:ss yyyy
 a| 
Abril 27 21:00:45 PST 2012



 a| 
fecha de finalización
 a| 
Hora de finalización de la operación de la base de datos en el formato mdd:hh:ss yyyy
 a| 
Abril 27 21:10:45 PST 2012



 a| 
estado
 a| 
Estado de la operación de base de datos
 a| 
Correcto

|===
Si no se proporciona ningún valor para las variables, SnapManager muestra el siguiente mensaje de error: Faltan valores -Subject.

. Introduzca el siguiente comando:
+
`smsap profile create -profileprofile [-profile-passwordprofile_password] -repository-dbnamerepo_service_name-hostrepo_host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port] [-rman {-controlfile | {-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname} } ] [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][ [ ]] [-notification [-success-emailemail_address1,email_address2-subjectsubject_pattern] [-failure-emailemail_address1,email_address2-subjectsubject_pattern]]`


