---
permalink: windows/task-clone-databases-from-backups.html 
sidebar: sidebar 
keywords: clone, database, backup, create, command 
summary: Es posible clonar una base de datos a partir de un backup con el comando clone create. 
---
= Clonar bases de datos a partir de backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible clonar una base de datos a partir de un backup con la `clone create` comando.



== Acerca de esta tarea

Primero debe crear un archivo de especificación del clon para la base de datos. SnapManager crea el clon según la información de este archivo de especificación.

Después de clonar una base de datos, es posible que desee actualizar el `tnsnames.ora` archivos en los equipos cliente con la nueva información de conexión de base de datos clonada. La `tnsnames.ora` Los archivos se utilizan para conectarse a una instancia de Oracle sin tener que especificar la información completa de la base de datos. SnapManager no actualiza el `tnsnames.ora` archivos.

SnapManager siempre crea un backup, incluidos los archivos de registro de archivos, si se utiliza el perfil creado con `-include-with-online-backups`. SnapManager permite clonar únicamente los backups completos de la base de datos.

SnapManager (3.2 o posterior) permite clonar los backups que contienen los archivos de datos y los archivos de registro de archivos.

Si el registro de archivos está disponible desde una ubicación externa, puede especificar la ubicación externa durante la clonado para recuperar la base de datos clonada en un estado coherente. Debe asegurarse de que Oracle pueda acceder a la ubicación externa. No se admite la clonado de backups de solo registro de archivos.

Aunque se crea el backup de registros de archivos junto con el backup parcial en línea, no se puede crear un clon de la base de datos con este backup.

Cuando se especifican las ubicaciones de los registros de archivos externos para recuperar la base de datos clonada en un estado coherente, debe asegurarse de incluir los nombres de las ubicaciones externas completamente en mayúsculas. En el sistema de archivos, los nombres de todas las carpetas y subcarpetas deben estar en mayúscula porque la base de datos Oracle convierte la ruta de destino en mayúscula y espera que las rutas de destino externas, los nombres de carpetas y los nombres de subcarpetas estén en mayúsculas. Si se especifican las rutas de destino de registros de archivo externos en minúscula, es posible que la base de datos no pueda identificar la ruta especificada y no se pueda recuperar la base de datos clonada.

Es posible clonar el backup de base de datos desde la ubicación de archivo de registro de archivos externo solo para una base de datos independiente.

Puede especificar el `-dump` opción como parámetro opcional para recoger los archivos de volcado después de la operación de creación de clones con errores o realizados correctamente.

*Clonación de copia de seguridad de archivo de datos sin copia de seguridad de archivo de registro*

Cuando el backup de archivos de datos no incluye el backup de registro de archivos, SnapManager para SAP clona la base de datos según el número de cambio del sistema (SCN) registrado durante el backup. Si no es posible recuperar la base de datos clonada, el `Archived log file for thread <number> and change <SCN> required to complete recovery` Se muestra un mensaje de error, aunque SnapManager para SAP sigue clonando la base de datos y, por último, se produce correctamente la creación del clon.

Al clonar con el backup de archivos de datos sin incluir el backup de registros de archivos, SnapManager recupera la base de datos clonada hasta el último SCN de registro de archivos, que se registra durante el backup.

.Pasos
. Cree un archivo de especificación del clon.
. Para crear un clon, introduzca el siguiente comando:
+
`+smsap clone create-backup-labelbackup_name-newsidnew_sid-labelclone_label-profileprofile_name-clonespecfull_path_to_clonespecfile [-taskspec _taskspec_] [-recover-from-location] path1 [,<path2>...]] [-dump]+`


