---
permalink: windows/task-clearing-user-credentials-for-all-hosts-repositories-and-profiles.html 
sidebar: sidebar 
keywords: clear, cache, credential, resource, host, repository, repositories, profile, delete, authenticate, host 
summary: 'Puede borrar la memoria caché de sus credenciales de los recursos \(hosts, repositorios y perfiles\). Esto elimina todas las credenciales de recursos del usuario que ejecuta el comando. Después de borrar la caché, debe volver a autenticar las credenciales para obtener acceso a estos recursos protegidos.' 
---
= Borrar credenciales de usuario para todos los hosts, repositorios y perfiles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede borrar la caché de sus credenciales para recursos (hosts, repositorios y perfiles). Esto elimina todas las credenciales de recursos del usuario que ejecuta el comando. Después de borrar la caché, debe volver a autenticar las credenciales para obtener acceso a estos recursos protegidos.

. Para borrar sus credenciales, introduzca el comando smsap credential clear de la CLI de SnapManager o seleccione *Admin* > *credenciales* > *Clear Cache* de la GUI de SnapManager.
. Salga de la interfaz gráfica de usuario de SnapManager.
+
NOTA:

+
** Si borró la caché de credenciales de la interfaz gráfica de usuario de SnapManager, no es necesario salir de la interfaz gráfica de usuario de SnapManager.
** Si borró la caché de credenciales de la interfaz de línea de comandos de SnapManager, debe reiniciar la interfaz gráfica de usuario de SnapManager.
** Si ha eliminado manualmente el archivo de credenciales cifrado, deberá reiniciar de nuevo la interfaz gráfica de usuario de SnapManager.


. Para volver a configurar las credenciales, repita el proceso con el fin de establecer las credenciales para el repositorio, el host del perfil y el perfil. Para obtener información adicional sobre cómo volver a configurar las credenciales de usuario, consulte "Configuración de credenciales tras borrar caché de credenciales".


*Información relacionada*

xref:reference-the-smosmsapcredential-clear-command.adoc[El comando smsap credential clear]
