---
permalink: windows/task-update-target-database-hostname-associated-with-a-profile.html 
sidebar: sidebar 
keywords: snapmanager, sap, provide, ability, update, host, name, target, database, profile, associate 
summary: 'SnapManager (3.2 o posterior) para SAP permite actualizar el nombre de host de la base de datos de destino en el perfil de SnapManager.' 
---
= Actualice el nombre de host de la base de datos de destino asociado a un perfil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager (3.2 o posterior) para SAP permite actualizar el nombre de host de la base de datos de destino en el perfil de SnapManager.



== Lo que necesitará

* El directorio inicial del usuario local debe tener en cuenta las asignaciones de perfil a repositorio.
* Se deben cerrar las sesiones de la interfaz gráfica de usuario (GUI) de SnapManager.




== Acerca de esta tarea

Puede actualizar el perfil con el nuevo nombre de host únicamente mediante la CLI.

*Escenarios no admitidos para cambiar el nombre de host de la base de datos de destino en Profile*

Las siguientes situaciones no son compatibles para cambiar el nombre de host de la base de datos de destino en el perfil:

* Cambiar el nombre de host de la base de datos de destino mediante la interfaz gráfica de usuario de SnapManager
* Reversión de la base de datos del repositorio después de actualizar el nombre de host de la base de datos de destino del perfil
* Actualizar varios perfiles para un nuevo nombre de host de base de datos de destino ejecutando un solo comando
* Cambiar el nombre de host de la base de datos de destino cuando se ejecuta cualquier operación de SnapManager



NOTE: Después de actualizar el nombre de host de la base de datos de destino en el perfil, solo se cambia el nombre de host de la base de datos de destino. Se conservan todos los demás parámetros de configuración establecidos en el perfil.

Después de actualizar el nombre de host de la base de datos de destino, no se puede eliminar ni desmontar el backup si el clon o el backup montado no están disponibles en el nuevo host. En tales situaciones, ejecutar las operaciones de SnapManager desde el host nuevo conlleva el fallo y las entradas obsoletas del host anterior. Para realizar operaciones de SnapManager, debe revertir al nombre de host anterior mediante el uso `profile update`.

.Pasos
. Introduzca el siguiente comando:
+
`*smsap profile update -profile _profile_ [-profile-password _profile_password_][-database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login-username _db_username_ -password _db_password_ -port _db_port_]] [{-rman{-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_}}} | -remove-rman] [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][-summary-notification] [-notification [-success -email _email_address1_, _email_address2_ -subject _subject_pattern_] [-failure -email _email_address1_, _email_address2_ -subject _subject_pattern_]] [-separate-archivelog-backups-retain-archivelog-backups -hours _hours_ | -days _days_ | -weeks _weeks_| -months _months_ [-protect [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`

+
Las demás opciones para este comando son las siguientes:

+
[`-force`] [`-noprompt`]

+
[`quiet` | `-verbose`]

+
|===
| Si desea... | Realice lo siguiente... 


 a| 
*Cambiar el nombre de host de la base de datos de destino*
 a| 
Especifique `-host _new_db_host_`

|===
. Para ver el nombre de host de la base de datos de destino del perfil, escriba el siguiente comando:
+
`smsap profile show`


