---
permalink: windows/task-customize-e-mail-subject-for-a-new-profile.html 
sidebar: sidebar 
keywords: customize, email, subject, profile, create, cusomtizing 
summary: Puede personalizar el asunto del correo electrónico para el nuevo perfil cuando lo cree. 
---
= Personalice el asunto del correo electrónico para un perfil nuevo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede personalizar el asunto del correo electrónico para el nuevo perfil cuando lo cree.



== Acerca de esta tarea

Puede personalizar el asunto del correo electrónico utilizando el patrón \{profile}_\{operation-name}_\{dB-sid}_\{dB-host}_\{start-date}_\{end-date}_\{status} o bien introducir su propio texto.

|===
| Nombre de la variable | Descripción | Valor de ejemplo 


 a| 
`profile`
 a| 
Nombre de perfil utilizado para la operación de base de datos
 a| 
PROF1



 a| 
`operation-name`
 a| 
Nombre de la operación de base de datos
 a| 
Backup, copia de seguridad de datos, copia de seguridad de registros de datos y archivos



 a| 
`db-sid`
 a| 
SID de la base de datos
 a| 
DB1



 a| 
`db-host`
 a| 
Nombre del servidor host
 a| 
Hosta



 a| 
`start-date`
 a| 
La hora de inicio de la operación de la base de datos en el formato mdd:hh:ss yyyy
 a| 
Abril 27 21:00:45 PST 2012



 a| 
`end-date`
 a| 
Hora de finalización de la operación de la base de datos en el formato mdd:hh:ss yyyy
 a| 
Abril 27 21:10:45 PST 2012



 a| 
`status`
 a| 
Estado de la operación de base de datos
 a| 
Correcto

|===
Si no se proporciona ningún valor para las variables, SnapManager muestra el siguiente mensaje de error: `Missing value(s) -subject`.

.Paso
. Introduzca el siguiente comando:
+
`*smsap profile create -profile _profile_ [-profile-password _profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login -username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login-username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login -username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname -pattern _pattern_][ [ ]] [-notification [-success -email _email_address1_, _email_address2_ -subject _subject_pattern_] [-failure -email _email_address1_, _email_address2_ -subject _subject_pattern_]]*`


