---
permalink: windows/task-disabling-email-notification-for-multiple-profiles.html 
sidebar: sidebar 
keywords: enable, summary, email, notification, multiple, profile, disable, alert, disabling 
summary: Después de activar la notificación de resumen por correo electrónico para varios perfiles, puede desactivarlos para que ya no reciban alertas por correo electrónico. 
---
= Desactivar la notificación por correo electrónico para varios perfiles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de activar la notificación de resumen por correo electrónico para varios perfiles, puede desactivarlos para que ya no reciban alertas por correo electrónico.

SnapManager permite deshabilitar la notificación de resumen por correo electrónico para esas operaciones de la base de datos ejecutadas por perfil. En la interfaz de línea de comandos de SnapManager, introduzca el comando notification remove-summary para deshabilitar la notificación por correo electrónico de resumen de varios perfiles, así como el nombre de la base de datos del repositorio para la cual no se requiere notificación por correo electrónico.

. Para deshabilitar la notificación de resumen de varios perfiles en una base de datos de repositorio, escriba el siguiente comando: `smsap notification remove-summary-notification -repository-portrepo_port-dbnamerepo_service_name-hostrepo_host-login-usernamerepo_username`


En el siguiente ejemplo se muestra la desactivación de la notificación de resumen para varios perfiles en una base de datos de repositorio:

[listing]
----

smsap notification remove-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login –username oba5
----