---
permalink: windows/task-resetting-profile-password.html 
sidebar: sidebar 
keywords: reset, profile, password, remember 
summary: Puede restablecer la contraseña del perfil si no recuerda la contraseña que ha proporcionado al crear el perfil. 
---
= Restablecimiento de la contraseña del perfil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede restablecer la contraseña del perfil si no recuerda la contraseña que ha proporcionado al crear el perfil.

* Debe asegurarse de que el servidor SnapManager esté en ejecución en la base de datos del repositorio.
* Debe tener las credenciales de administrador local del host en el que reside la base de datos del repositorio.
* Debe asegurarse de que el perfil no esté en uso para ninguna operación cuando se restablezca la contraseña para ese perfil.


Puede restablecer la contraseña desde la interfaz de línea de comandos o desde la interfaz gráfica de usuario de SnapManager. Al restablecer la contraseña, SnapManager consulta al servidor SnapManager en el host de repositorios para identificar el sistema operativo para el host de repositorios. Debe introducir las credenciales de usuario autorizado para conectarse con el host de repositorios. El servidor SnapManager autentica a los usuarios con sus credenciales de administrador local en la base de datos de repositorios. Cuando la autenticación se realiza correctamente, SnapManager restablece la contraseña del perfil en el servidor SnapManager con la nueva contraseña.


NOTE: SnapManager no mantiene el historial de las operaciones de restablecimiento de contraseña.

. Restablezca la contraseña del perfil. Para ello, introduzca el siguiente comando:
+
`smsap password reset -profileprofile [-profile-passwordprofile_password] [-repository-hostadmin-passwordadmin_password]`


