---
permalink: windows/task-updating-the-existing-repository.html 
sidebar: sidebar 
keywords: update, exist, repository, upgrading, upgrade, snapmanager, path, updating 
summary: No es necesario actualizar el repositorio existente si va a actualizar de SnapManager 3.3.x a SnapManager 3.4 o posterior pero para el resto de las rutas de actualización debe actualizar el repositorio existente para poder acceder a él después de la actualización. 
---
= Actualizando el repositorio existente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
No es necesario actualizar el repositorio existente si va a actualizar de SnapManager 3.3.x a SnapManager 3.4 o posterior pero para el resto de las rutas de actualización debe actualizar el repositorio existente para poder acceder a él después de la actualización.

* El servidor SnapManager actualizado debe haberse iniciado y verificado.
* Debe existir un backup del repositorio existente.
* Si va a actualizar desde cualquier versión anterior a SnapManager 3.1 a SnapManager 3.3 o posterior, primero debe actualizar a SnapManager 3.2.
+
Después de actualizar a SnapManager 3.2, puede actualizar a SnapManager 3.3 o una versión posterior.

* Después de actualizar el repositorio, no se puede utilizar el repositorio con una versión anterior de SnapManager.
+
.. Actualice el repositorio existente: `smsap repository update -repository -dbname repository_service_name -host repository_host_name -login -username repository_user_name -port repository_port`
+
*** El nombre de usuario del repositorio, el nombre de servicio del repositorio y el nombre de host del repositorio pueden consistir en caracteres alfanuméricos, un signo menos, un guión bajo y un punto.
*** El puerto del repositorio puede ser cualquier número de puerto válido. Las demás opciones utilizadas durante la actualización del repositorio existente son las siguientes:
*** La opción de fuerza
*** La opción noprompt
*** La opción silenciosa
*** La opción verbose




+
[listing]
----
smsap repository update -repository -dbname HR1
-host server1 -login -username admin -port 1521
----


Reinicie el servidor SnapManager para reiniciar todas las programaciones asociadas.
