---
permalink: windows/task-add-new-profile-to-summary-notification.html 
sidebar: sidebar 
keywords: configure, summary, email, notification, repository, database, profile, command, add 
summary: Después de configurar una notificación por correo electrónico de resumen para la base de datos de repositorio, puede agregar un nuevo perfil a la notificación de resumen utilizando el comando summary notification. 
---
= Añada un nuevo perfil a las notificaciones por correo electrónico de resumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de configurar una notificación de resumen por correo electrónico para la base de datos del repositorio, puede agregar un nuevo perfil a la notificación de resumen mediante el `summary notification` comando.

.Paso
. Introduzca el siguiente comando:
+
`*smsap profile create -profile _profile_name_ [-profile-password _profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login- username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login -username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login -username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] [-retain [-hourly -count _n_] [-duration _m_]] [-daily -count _n_] [-duration _m_]] [-weekly -count _n_] [-duration _m_]] [-monthly -count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][ [ ]] [-summary-notification]*`

+
Las demás opciones para este comando son las siguientes:

+
[`-force`]

+
[`quiet` | `-verbose`]


