---
permalink: windows/task-delete-backups.html 
sidebar: sidebar 
keywords: delete, backup, free, space, occupy, remove, snapshot, copies, copy, volume 
summary: Debe eliminar backups cuando ya no los necesite, lo que libera el espacio que estos backups ocupan. Si elimina los backups, reducirá la posibilidad de alcanzar el límite de 255 copias snapshot por volumen. 
---
= Eliminar backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe eliminar backups cuando ya no los necesite, lo que libera el espacio que estos backups ocupan. Si elimina los backups, reducirá la posibilidad de alcanzar el límite de 255 copias snapshot por volumen.



== Lo que necesitará

* Debe asegurarse de que el backup no se haya usado para crear un clon.




== Acerca de esta tarea

Puede eliminar backups retenidos de forma ilimitada sin cambiar la clase de retención.

Opcionalmente, es posible recoger los archivos de volcado después de la operación de eliminación de backup exitosa o con errores.

Si desea eliminar los backups de registros de archivos, debe comprobar la duración de retención establecida para el backup de registros de archivos. Si el backup de registros de archivos se encuentra dentro de la duración de retención y se requieren archivos de registro de archivos para la recuperación de una base de datos restaurada, no se puede eliminar el backup de registros de archivos.

.Pasos
. Compruebe que las operaciones se han completado introduciendo el comando siguiente:
+
`*smsap operation list -profile _profile_name_-dump -quiet -verbose*`

. Para eliminar un backup, introduzca el siguiente comando:
+
`*smsap backup delete -profile _profile_name_ [-label _label_ [data | -archivelogs] | -id _id_ | -all] [-force] [ -dump] [-quiet | -verbose]*`

+
Utilice la `-force` opción para forzar la eliminación del backup. Forzar la eliminación de un backup que tenga operaciones incompletas podría dejar el backup en estado incoherente.


