---
permalink: windows/task-creating-backup-schedules.html 
sidebar: sidebar 
keywords: schedule, backup, time, frequency, suit, data, environment, creating, create 
summary: Es posible programar un backup en el momento y la frecuencia que sean adecuados para sus datos y entorno. 
---
= Creando programaciones de backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible programar un backup en el momento y la frecuencia que sean adecuados para sus datos y entorno.

Desde SnapManager 3.2 para SAP, puede programar las copias de seguridad de los archivos de registro de archivos por separado. Sin embargo, debe utilizar el perfil que ha creado para separar los archivos de registro de archivos.

Si programó los backups de los archivos de datos y los archivos de registro de archivos al mismo tiempo, SnapManager creará primero el backup de los archivos de datos.

Si selecciona el intervalo de programación como -onetimeonly, todas las opciones de eliminación estarán disponibles. Si selecciona un intervalo de programación distinto de -onetime only, no se admiten las opciones de eliminación -until-SCN y -until-date y se muestra el siguiente mensaje de error: La opción de eliminación del registro de archivado especificada, -until-scn o -until-date para el intervalo por hora de programación no es válida. Especifique la opción -onetimeonly para el intervalo de programación o pine los registros de archivo utilizando cualquiera de las opciones all, o -before {-months | -days | -weeks| -hours}.

Cuando se produce una conmutación por error en los entornos de Microsoft Windows Server Failover Cluster (WSFC) y Microsoft Cluster Server (MSCS), debe reiniciar el servidor SnapManager para SAP de modo que la dirección del servicio (virtual) se asigne al host activo y las programaciones de SnapManager se ajusten al host SnapManager activo.


NOTE: Si existe el mismo perfil y nombre de programación en otro repositorio, no se inicia la operación de programación de backup en ese repositorio. Se cerrará la operación con el siguiente mensaje: Ya se está ejecutando.

. Introduzca el siguiente comando: `smsap schedule create -profile profile_name {[-full {-online | -offline | -auto}[-retain [-hourly | -daily | -weekly | -monthly | -unlimited] [-verify]] | [-data [-filesfiles [files]] | [-tablespaces-tablespaces [-tablespaces]] {-online | -offline | -auto}[-retain [-hourly | -daily | -weekly | -monthly | -unlimited] [-verify]] | [-archivelogs]} [-commentcomment][-backup-destpath1 [,[path2]] [-exclude-destpath1 [,path2]] [-prunelogs{-all | -untilSCNuntilSCN | -until-dateyyyy-MM-dd HH:mm:ss | -before {-months | -weeks | -days | -hours}} -prune-destprune_dest1,prune_dest2] -schedule-nameschedule_name [-schedule-commentschedule_comment] -interval {-hourly | -daily | -weekly | -monthly | -onetimeonly} -cronstringcronstring-start-time {start-timestart_time <yyyy-MM-dd HH:mm\>} -runasuser-runasuser [-force] [-taskspec-taskspec] [-quiet | -verbose]`
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
*Programar una copia de seguridad de una base de datos en línea o sin conexión*
 a| 
Especifique -offline o -online para programar un backup de la base de datos sin conexión o en línea. Si especifica las opciones, no se puede utilizar -auto.



 a| 
*Deje que SnapManager gestione la programación de una base de datos independientemente de si está en línea o sin conexión*
 a| 
Especifique -auto. Si especifica -auto, no puede utilizar --offline o -online.



 a| 
*Programar una copia de seguridad de archivos de datos*
 a| 
Especifique -data -files para enumerar los archivos separados por comas. Por ejemplo, utilice los nombres de archivo f1,f2,f3.



 a| 
*Programar una copia de seguridad parcial de tablespaces específicos*
 a| 
Especifique -tablespaces para enumerar los tablespaces separados por comas. Por ejemplo, utilice ts1,ts2,ts3.



 a| 
*Programar copia de seguridad de archivos de registro de archivo*
 a| 
Especifique lo siguiente:

** -archivelogs para programar la copia de seguridad de los archivos de registro de archivo
** -backup-dest para programar los destinos de archivos de registro de archivos que se incluirán en el backup
** -exclude-dest para programar los destinos de registro de archivos que se excluirán del backup




 a| 
*Especifique los valores de la clase de retención*
 a| 
Especifique -retain e indique si el backup debe conservarse de acuerdo con una de las siguientes clases de retención:

** -cada hora
** - diariamente
** -semanal
** -mensual
** -El valor predeterminado de SnapManager ilimitado es cada hora.




 a| 
*Programar la eliminación de archivos de registro de archivos*
 a| 
Especifique lo siguiente: ** -Prunelogs para afinar los archivos de registro de archivos mientras se programa una copia de seguridad ** -prune-dest para especificar el destino de registro de archivos desde el que se recortan los archivos de registro de archivos



 a| 
*Incluya un nombre para el horario*
 a| 
Especifique -schedule-nombre.



 a| 
*Programar copia de seguridad de la base de datos en un intervalo de tiempo específico*
 a| 
Especifique la opción INTERVAL y seleccione el intervalo de tiempo entre las siguientes, mediante el cual deben crearse los backups:

** -cada hora
** - diariamente
** -semanal
** -mensual
** -untimeonly




 a| 
*Configurar un horario*
 a| 
Especifique -cronstring e incluya las siguientes siete subexpresiones que describen la opción individual:

** 1 se refiere a segundos.
** 2 se refiere a minutos.
** 3 se refiere a horas.
** 4 se refiere a un día en un mes.
** 5 se refiere al mes.
** 6 se refiere a un día en una semana.
** (Opcional) 7 se refiere al año. *Nota:* Si programó su copia de seguridad con diferentes horas en -cronstring y -start-time, entonces la programación de la copia de seguridad se sobrescribe y se activa por la -start-time.




 a| 
*Agregar un comentario sobre el programa de copia de seguridad*
 a| 
Specify -schedule-comment seguido de la cadena de descripción.



 a| 
*Especifique la hora de inicio de la operación de programación*
 a| 
Especifique -start-time en el formato yyyy-mm-dd hh:mm.



 a| 
*Cambiar el usuario de la operación de copia de seguridad programada mientras se programa la copia de seguridad*
 a| 
Especifique -runasuser. La operación se ejecuta como el usuario (usuario raíz o usuario de Oracle) que creó la programación. Sin embargo, puede utilizar su propio ID de usuario si tiene credenciales válidas tanto para el perfil de base de datos como para el host.



 a| 
*Active una actividad de tareas previas o posteriores a la tarea de la operación de programación de copia de seguridad mediante el archivo XML de especificación de tareas previas y posteriores*
 a| 
Especifique la opción -taskspec y proporcione la ruta absoluta del archivo XML de la especificación de la tarea para realizar un preprocesamiento o una actividad de post-procesamiento que tenga lugar antes o después de la operación de programación de copia de seguridad.

|===

