---
permalink: unix-administration/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, role-base, access, control, rbac, credential, management 
summary: 'Puede gestionar la seguridad en SnapManager aplicando autenticación de usuario y control de acceso basado en roles (RBAC). El método de autenticación de usuario permite acceder a recursos como repositorios, hosts y perfiles. El control de acceso basado en roles permite restringir las operaciones que SnapManager puede realizar en los volúmenes y LUN que contienen los archivos de datos de la base de datos.' 
---
= Seguridad y gestión de credenciales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede gestionar la seguridad en SnapManager aplicando la autenticación del usuario y el control de acceso basado en roles (RBAC). El método de autenticación de usuario permite acceder a recursos como repositorios, hosts y perfiles. El control de acceso basado en roles permite restringir las operaciones que SnapManager puede realizar en los volúmenes y LUN que contienen los archivos de datos de la base de datos.

Cuando se realiza una operación mediante la interfaz de línea de comandos (CLI) o la interfaz gráfica de usuario (GUI), SnapManager recupera las credenciales establecidas para repositorios y perfiles. SnapManager guarda las credenciales de instalaciones anteriores.

El repositorio y los perfiles se pueden proteger con una contraseña. Una credencial es la contraseña configurada para el usuario de un objeto y la contraseña no está configurada en el objeto en sí.

Puede gestionar la autenticación y las credenciales realizando las siguientes tareas:

* Gestione la autenticación de usuario mediante solicitudes de contraseña en las operaciones o mediante el `smsap credential set` comando.
+
Configurar credenciales para un repositorio, host o perfil.

* Vea las credenciales que rigen los recursos a los que tiene acceso.
* Borre las credenciales de un usuario para todos los recursos (hosts, repositorios y perfiles).
* Eliminar credenciales de un usuario para recursos individuales (hosts, repositorios y perfiles).


Para gestionar el acceso basado en roles, debe realizar las siguientes tareas:

* Habilite RBAC para SnapManager mediante SnapDrive.
* Asigne usuarios a las funciones y establezca las funciones mediante la consola de Operations Manager.
* De manera opcional, habilite SnapManager para almacenar contraseñas cifradas mediante la edición de `smsap.config file`.


Si está instalado Protection Manager, el acceso a las funciones se ve afectado de las siguientes maneras:

* Si se instala Protection Manager, al crear un perfil de base de datos, SnapManager crea un conjunto de datos y rellena el conjunto de datos con los volúmenes que contienen los archivos de base de datos.
+
Después de una operación de backup, SnapManager mantiene el contenido del conjunto de datos sincronizado con los archivos de la base de datos.

* Si Protection Manager no está instalado, SnapManager no puede crear un conjunto de datos y no podrá establecer la protección en los perfiles.

