---
permalink: unix-administration/concept-profile-usage-for-br-tools-backups.html 
sidebar: sidebar 
keywords: backint, snapmanager, profile, repository, backup 
summary: Cuando ejecuta un comando BR*Tools que usa la interfaz BACKINT, SnapManager usa un perfil del repositorio. El repositorio está determinado por las credenciales SnapManager del usuario que ejecuta el comando BR*Tools. 
---
= Uso del perfil para copias de seguridad BR*Tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando ejecuta un comando BR*Tools que usa la interfaz BACKINT, SnapManager usa un perfil del repositorio. El repositorio está determinado por las credenciales SnapManager del usuario que ejecuta el comando BR*Tools.

De forma predeterminada, SnapManager utiliza el perfil con el mismo nombre que el identificador de sistema de base de datos SAP.



== Acerca de la creación de credenciales para acceder al repositorio

Puede utilizar el `smsap credential set` Para establecer las credenciales del repositorio para el usuario BR*Tools.



== Especificar un nombre de perfil de SnapManager diferente

Siempre que el identificador del sistema sea único para todos los hosts cuyos perfiles de SnapManager se encuentren en un repositorio determinado, el nombre del perfil predeterminado será suficiente. Puede crear el perfil de SnapManager y llamarlo mediante el valor identificador del sistema de la base de datos.

Sin embargo, si se utiliza el mismo identificador de sistema en distintos hosts, o si desea especificar más de un perfil SnapManager para utilizarlo con BR*Tools en una instancia SAP determinada, deberá definir el nombre del perfil para los comandos BR*Tools.

Las operaciones de base de datos programadas en la aplicación SAP se ejecutan como usuario. Las operaciones BR*Tools programadas dentro de las aplicaciones SAP se ejecutan como `sidadm`. Estos usuarios deben tener acceso al repositorio y al perfil.

Para configurar las credenciales de un usuario, realice los siguientes pasos:

. Inicie sesión como `sidadm`.
. Introduzca el comando para establecer las credenciales del repositorio:
+
`*smsap credential set command*`

. Sincronice los perfiles introduciendo el siguiente comando:
+
`*smsap profile sync*`

. Establezca la contraseña de los perfiles detectados introduciendo el comando:
+
`*smsap credential set*`





== Acerca de la creación del archivo de parámetros de la utilidad de copia de seguridad

El comando BR*Tools puede pasar opcionalmente un archivo de parámetros de utilidad de copia de seguridad (.utl Parameter) a la interfaz BACKINT. De forma predeterminada, el nombre de este archivo es `initSID.utl`, Donde SID es el identificador de sistema de la base de datos.

De manera predeterminada, BR*Tools usa el archivo de parámetros especificado por `_util_par_file_` en la `initSID.sap file`. El archivo de parámetros de la utilidad de copia de seguridad se almacena normalmente en el mismo directorio que el `initSID.sap file`.

Agregar `profile_name = <profile>` para la `.utl` archivos y guardar. La `_profile_` Es el nombre del perfil SnapManager que desea utilizar para los comandos BR*Tools.

En la siguiente tabla se enumeran los parámetros adicionales de la utilidad de copia de seguridad incluidos en la `.utl` archivos para operaciones como la retención de backups, la restauración rápida y la protección de datos:

[cols="1a,3a"]
|===
| Operaciones | Parámetros de la utilidad de copia de seguridad 


 a| 
Retención de backups
 a| 
* Clave: Retener
* Valor: Ilimitado | horario | diario | semanal | mensual




 a| 
Restauración rápida
 a| 
* Tecla: Rápido
* Valor: Requerir | anular | respaldo | desactivado




 a| 
Protección de datos
 a| 
* Clave: Proteger
* Valor: sí | no | se deja en blanco



NOTE: Las diferentes opciones mencionadas para el parámetro Value son similares a las `-protect` opción que se utiliza en la interfaz de línea de comandos.



 a| 
Realice backups de datos del almacenamiento secundario en una ubicación definida según las preferencias de los usuarios
 a| 
* Key: Preferred_backup_locations
* Valor: Los nombres de nodos de protección de datos como una lista separada por comas.
* Valor predeterminado: No se ha establecido ningún valor.



NOTE: Para añadir un nombre de nodo de política de protección de datos, consulte xref:concept-about-different-protection-policies.adoc[Acerca de las descripciones de políticas de protección].



 a| 
Restaure los datos del almacenamiento secundario a una ubicación preferida
 a| 
* Key: Restore_from_Latter_backup_location
* Valor: sí | no
* Valor predeterminado: sí


|===
En la siguiente tabla se describen los diferentes parámetros de la utilidad de backup para estas operaciones:

[cols="1a,1a,1a"]
|===
| Funcionamiento | Clave | Valor 


 a| 
Retención de backups
 a| 
rápido=
 a| 
respaldo



 a| 
Restauración rápida
 a| 
retener=
 a| 
cada hora



 a| 
Protección de datos
 a| 
proteger=
 a| 
no

|===


== Adición del parámetro de utilidad de copia de seguridad al archivo de inicialización BR*Tools

SAP crea un archivo de perfil de copia de seguridad denominado `initSID.sap` Para cada instancia de base de datos SAP en `$ORACLE_HOME/dbs/`. Puede usar este archivo para especificar el parámetro predeterminado de la utilidad de copia de seguridad (`.utl`) Archivo utilizado para comandos BR*Tools.

. Edite el `initSID.sap` archiva y localiza la línea que comienza con `util_par_file =`.
. Anule el comentario de esta línea y agregue la ruta al archivo de parámetros de la utilidad de copia de seguridad que contiene el nombre del perfil, por ejemplo, `util_par_file = initSA1.utl`.
. Si especifica un valor para `util_par_file`, asegúrese de que el archivo existe.
+
Si no se encuentra el archivo, los comandos BRBACKUP fallan porque intentan incluir ese archivo en una copia de seguridad.



Si se encuentra alguna de las siguientes condiciones de error, deberá utilizar el `-u` opción como nombre de perfil:

* `Parameter files does not exist`
* `No profile_name entry`


Tanto orasid como sidadm necesitan tener acceso al perfil que se utilizaría para crear o gestionar copias de seguridad creadas con BR*Tools.



== Especificar el nombre del archivo del parámetro de la utilidad de copia de seguridad en el comando BR*Tools

Opcionalmente, puede especificar el archivo de parámetros de utilidad de copia de seguridad (.utl Parameter) en los comandos BR*Tools con la opción -r . El valor de la línea de comandos anula el valor especificado en el archivo de inicialización SAP.

BR*Tools busca el archivo de parámetros en `$ORACLE_HOME/dbs/` directorio. Si almacena el archivo en otra ubicación, debe proporcionar la ruta completa con la opción -r. Por ejemplo:

`*+brbackup -r /opt/NetApp_fcp_price_10g_enterprise_inst_vol1/dbs/initCER.utl ...+*`
