---
permalink: unix-administration/reference-troubleshooting-snapdrive-issues.html 
sidebar: sidebar 
keywords: common, issue, snapmanager, snapdrive, troubleshooting, product 
summary: Puede que tenga algunos problemas comunes al utilizar SnapManager con productos de SnapDrive. 
---
= Resolución de problemas de SnapDrive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede que tenga algunos problemas comunes al utilizar SnapManager con productos de SnapDrive.

En primer lugar, debe determinar si el problema está relacionado con SnapManager para SAP o SnapDrive. Si el problema es un error de SnapDrive, SnapManager para SAP muestra un mensaje de error similar al siguiente:

[listing]
----
SMSAP-12111: Error executing snapdrive command "<snapdrive command>": <snapdrive error>
----
A continuación se muestra un ejemplo de un mensaje de error de SnapDrive en el que `SMSAP-12111` Es el número de error SnapManager. La `0001-770` El esquema de numeración representa los errores de SnapDrive para UNIX.

[listing]
----
SMSAP-12111: Error executing snapdrive command
"/usr/sbin/snapdrive snap restore -file
/mnt/pathname/ar_anzio_name_10gR2_arrac1/data/undotbs02.dbf -snapname pathname.company.com:
/vol/ar_anzio_name_10gR2_arrac1:
TEST_ARRAC1_YORKTOW_arrac12_F_C_0_8abc01b20f9ec03d010f9ec06bee0001_0": 0001-770
Admin error: Inconsistent number of files returned when listing contents of
/vol/ar_anzio_name_10gR2_arrac1/.snapshot/
TEST_ARRAC1_YORKTOW_arrac12_F_C_0_8abc01b20f9ec03d010f9ec06bee0001_0/data
on filer pathname.
----
A continuación, se muestran los mensajes de error más comunes de SnapDrive para UNIX relacionados con la detección de LUN, los problemas de configuración y el espacio. Si recibe alguno de estos errores, consulte el capítulo solución de problemas de la _Guía de instalación y administración de SnapDrive_.

[cols="3a,1a"]
|===
| Síntoma | Explicación 


 a| 
``0001-136 Admin error: Unable to log on to filer: <filer> Please set user name and/or password for <filer>``
 a| 
Configuración inicial de SnapDrive



 a| 
`0001-382 Admin error: Multipathing rescan failed`
 a| 
Error de detección de LUN



 a| 
`0001-462 Admin error: Failed to unconfigure multipathing for <LUN>: spd5: cannot stop device. Device busy.`
 a| 
Error de detección de LUN



 a| 
``0001-476 Admin error: Unable to discover the device associated with ... 0001-710 Admin error: OS refresh of LUN failed ...``
 a| 
Error de detección de LUN



 a| 
``0001-680 Admin error: Host OS requires an update to internal data to allow LUN creation or connection. Use 'snapdrive config prepare luns' or update this information manually...``
 a| 
Error de detección de LUN



 a| 
`0001-817 Admin error: Failed to create volume clone ... : FlexClone not licensed`
 a| 
Configuración inicial de SnapDrive



 a| 
``0001-878 Admin error: HBA assistant not found. Commands involving LUNs should fail.``
 a| 
Error de detección de LUN

|===