---
permalink: unix-administration/reference-the-smosmsapcredential-set-command.html 
sidebar: sidebar 
keywords: command, credentials, user, access, resource, secure, host, repositories, repository, database, profile, snapmanager, run, password, smsap 
summary: Este comando permite establecer las credenciales para que los usuarios accedan a recursos seguros, como hosts, repositorios y perfiles de bases de datos. La contraseña del host es la contraseña del usuario en el host en el que se ejecuta SnapManager. La contraseña del repositorio es la contraseña del usuario de Oracle que contiene el esquema del repositorio de SnapManager. La contraseña del perfil es una contraseña compuesta por la persona que crea el perfil. Para las opciones de host y repositorio, si no se incluye la opción -password opcional, se le pedirá que introduzca una contraseña del tipo especificado en los argumentos de comando. 
---
= El comando smsap credential set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando permite establecer las credenciales para que los usuarios accedan a recursos seguros, como hosts, repositorios y perfiles de bases de datos. La contraseña del host es la contraseña del usuario en el host donde se ejecuta SnapManager. La contraseña del repositorio es la contraseña del usuario de Oracle que contiene el esquema del repositorio de SnapManager. La contraseña del perfil es una contraseña compuesta por la persona que crea el perfil. Para las opciones del host y del repositorio, si es opcional `-password` no se incluye la opción, se le pedirá que introduzca una contraseña del tipo especificado en los argumentos de comando.



== Sintaxis

[listing, subs="+macros"]
----
pass:quotes[smsap credential set
[-host
-name _host_name_
-username _username_\]
[-password _password_\] \] |
[-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_\] [-password _repo_password_\] \]
-port _repo_port_ |
[-profile
-name _profile_name_\]
[-password _password_\] \]
[-quiet | -verbose]]
----


== Parámetros

* `*-host _hostname_*`
+
Especifica el nombre o la dirección IP del servidor host en el que se ejecuta SnapManager.

+
La `-host` el parámetro incluye las siguientes opciones:

+
** `-name _host_name_`: Especifica el nombre del host para el que se establecerá la contraseña.
** `-username _user_name_`: Especifica el nombre de usuario en el host.
** `-password _password_` Especifica la contraseña del usuario en el host.


* `*-repository -dbname*`
+
Especifica el nombre de la base de datos que almacena el perfil. Utilice el nombre global o el SID.

+
La `-repository` el parámetro incluye las siguientes opciones:

+
** `-dbname _repo_service_name_`: Especifica el nombre de la base de datos que almacena el perfil. Utilice el nombre global o el SID.
** `-host _repo_host_`: Especifica el nombre o la dirección IP del servidor host en el que se ejecuta la base de datos de repositorio.
** `-login-username _repo_username_`: Especifica el nombre de usuario necesario para tener acceso a la base de datos que almacena el repositorio.
** `-password _password_`: Especifica la contraseña necesaria para tener acceso a la base de datos que almacena el repositorio.
** `-port _repo_port_`: Especifica el número de puerto TCP utilizado para acceder a la base de datos que almacena el repositorio.


* `*-profile -name _profile_name_*`
+
Especifica el perfil con el que está asociada la base de datos.

+
La `-profile` el parámetro incluye la siguiente opción:

+
** `-name _profilename_`: Especifica el nombre del perfil para el que se establecerá la contraseña.
** `-password _password_`: Especifica la contraseña necesaria para acceder al perfil.


* `*-quiet*`
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* `*-verbose*`
+
Muestra mensajes de error, advertencia e informativos en la consola.



'''


== Ejemplo de comando para configurar las credenciales del repositorio

En el ejemplo siguiente se establecen credenciales para un repositorio.

[listing]
----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----
[listing]
----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----
'''
'''


== Ejemplo de comando para configurar las credenciales del host

Dado que las credenciales de host representan una credencial real del sistema operativo, deben incluir el nombre de usuario además de la contraseña.

[listing]
----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----
'''