---
permalink: unix-administration/reference-the-smosmsapcredential-delete-command.html 
sidebar: sidebar 
keywords: command, delete, user, credentials, secure, resource, smsap 
summary: Este comando elimina las credenciales de usuario de un recurso protegido en particular. 
---
= El comando smsap credential delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando elimina las credenciales de usuario de un recurso protegido en particular.



== Sintaxis

[listing, subs="+macros"]
----
pass:quotes[smsap credential delete
[-host -name _host_name_
-username _username_\] |
[-repository
-dbname _repo_service_name_
-host _repo_host_
-login -username _repo_username_
-port _repo_port_\] |
[-profile
-name _profile_name_\]
[-quiet | -verbose]]
----


== Parámetros

* `*-host _hostname_*`
+
Especifica el nombre del servidor host en el que se ejecuta SnapManager.

+
La `-host` el parámetro incluye las siguientes opciones:

+
** `-name _host_name_`: Especifica el nombre del host para el que se eliminará la contraseña.
** `-username _user_name_`: Especifica el nombre de usuario en el host.


* `*-repository -dbname*`
+
Especifica el nombre de la base de datos que almacena el perfil. Utilice el nombre global o el SID.

+
La `-repository` el parámetro incluye las siguientes opciones:

+
** `-dbname _repo_service_name_`: Especifica el nombre de la base de datos que almacena el perfil. Utilice el nombre global o el SID.
** `-host _repo_host_`: Especifica el nombre o la dirección IP del servidor host en el que se ejecuta la base de datos de repositorio.
** `-login-username _repo_username_`: Especifica el nombre de usuario necesario para tener acceso a la base de datos que almacena el repositorio.
** `-port _repo_port_`: Especifica el número de puerto TCP utilizado para acceder a la base de datos que almacena el repositorio.


* `*-profile -name _profile_name_*`
+
Especifica el perfil con el que está asociada la base de datos.

+
La `-profile` el parámetro incluye la siguiente opción:

+
** `-name _profilename_`: Especifica el nombre del perfil para el que se eliminará la contraseña.


* `*-quiet*`
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* `*-verbose*`
+
Muestra mensajes de error, advertencia e informativos en la consola.



'''


== Comando de ejemplo

En este ejemplo se eliminan las credenciales del perfil.

[listing]
----
smsap credential delete -profile -name user1 -verbose
----
[listing]
----
SMSAP-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
En este ejemplo, se eliminan las credenciales del repositorio.

[listing]
----
smsap credential delete -repository -dbname SMSAPREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMSAP-20023 [INFO ]: Deleted repository credentials for "user1@SMSAPREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
En este ejemplo, se eliminan las credenciales del host.

[listing]
----
smsap credential delete -host -name Host2
----
[listing]
----
SMSAP-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
'''