---
permalink: unix-administration/reference-the-smosmsapbackup-verify-command.html 
sidebar: sidebar 
keywords: run, backup, verify, command, oracle, smsap 
summary: Es posible ejecutar el comando backup verify para ver si el backup está en un formato válido para Oracle. 
---
= El comando smsap backup verify
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede ejecutar el `backup verify` Comando para ver si el backup tiene un formato válido para Oracle.



== Sintaxis

[listing, subs="+macros"]
----
pass:quotes[smsap backup verify
-profile _profile_name_
[-label _backup_name- | [-id _guid_\]
[-retain {-hourly | -daily | -weekly | -monthly | -unlimited}\] [-force\]
[-dump\] [-quiet | -verbose\]]
----


== Parámetros

* ``*-profile _profile_name_*``
+
Especifica el perfil para el que desea verificar un backup. El perfil contiene el identificador de la base de datos y otra información de la base de datos.

* ``*-id _guid_*``
+
Verifica el backup con el GUID especificado. SnapManager genera el GUID cuando se crea un backup. Puede utilizar el comando smsap backup list para mostrar el GUID de cada copia de seguridad.

* ``*-label _label_name_*``
+
Verifica el backup con la etiqueta especificada.

* ``*-dump*``
+
Recopila los archivos de volcado después de la operación de verificación de backup realizada correctamente o con errores.

* ``*-force*``
+
Fuerza a la base de datos al estado necesario para realizar la operación de verificación.

* ``*-quiet*``
+
Muestra sólo mensajes de error en la consola. El valor predeterminado es mostrar mensajes de error y advertencia.

* ``*-verbose*``
+
Muestra mensajes de error, advertencia e informativos en la consola.



'''


== Ejemplo

A continuación se muestra un ejemplo de verificación del backup:

[listing]
----
smsap backup verify -profile SALES1 -label full_backup_sales_May -quiet
----
[listing]
----
DBVERIFY - Verification starting : FILE = +SMSAP_1_1161675083835/smsmsap/datafile/data.277.582482539 ...
----
'''