---
permalink: unix-administration/reference-error-messages.html 
sidebar: sidebar 
keywords: information, error, message, associate, snapmanager, operation 
summary: Es posible encontrar información sobre los mensajes de error asociados a diferentes operaciones de SnapManager. 
---
= Mensajes de error
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible encontrar información sobre los mensajes de error asociados a diferentes operaciones de SnapManager.



== Mensajes de error más comunes

En la siguiente tabla se enumeran algunos de los errores más comunes e importantes asociados con SnapManager para SAP:

[cols="1a,1a,1a"]
|===
| Mensaje de error | Explicación | Resolución 


 a| 
`SD-10038: File system is not writable.`
 a| 
El proceso de SnapManager no tiene acceso de escritura al sistema de archivos.
 a| 
Debe asegurarse de que el proceso de SnapManager tenga acceso de escritura al sistema de archivos. Después de corregir esto, es posible que deba tomar otra instantánea.



 a| 
`SMSAP-05075: Unable to create Profile. You must configure the DP/XDP relationship properly or choose the correct protection policy per the underlying relationship.`
 a| 
Los volúmenes subyacentes no están en una relación de SnapVault ni de SnapMirror.
 a| 
Debe configurar una relación de protección de datos entre los volúmenes de origen y de destino, e inicializar la relación.



 a| 
`[SMSAP-05503] You have specified the same name to the profile. Specify a different name to rename the profile.`
 a| 
Los perfiles con nombres idénticos no pueden existir en un repositorio.
 a| 
Introduzca un nombre de perfil que no esté en uso.



 a| 
`SMSAP-05505: Unable to update dataset metadata.`
 a| 
Es posible que el conjunto de datos se haya eliminado o no exista.
 a| 
Antes de actualizar los metadatos del conjunto de datos, compruebe que el conjunto de datos existe mediante la consola de gestión de NetApp.



 a| 
`SMSAP-05506: You cannot update the profile since there are operation(s) running on the profile. You must wait until the operation(s) complete and then update the profile`
 a| 
El perfil no se puede actualizar cuando hay operaciones de backup, restauración y clonado en curso.
 a| 
Actualice el perfil una vez completada la operación actual.



 a| 
`SMSAP-05509: Invalid archivelog primary retention duration - Specify a positive integer value.`
 a| 
La duración de la retención de los backups de registros de archivos no puede ser negativa.
 a| 
Especifique un valor positivo para la duración de la retención de los backups de registros de archivos.



 a| 
`SMSAP-07463: This backup restore requires the database to be in required state. Failed to bring the database to the required state.`
 a| 
La base de datos no está en el estado requerido para una operación de backup.
 a| 
Compruebe que la base de datos esté en estado relevante antes de crear una copia de backup. El estado de la base de datos que se va a restaurar depende del tipo de proceso de restauración que se desee realizar y del tipo de archivos que se incluirán.



 a| 
`SMSAP-09315: After performing repository upgrade or update operation, you might not receive the summary notification for notifications set in previous version unless you update the summary notification with the notification host details.`
 a| 
Los ajustes de notificación no se configuran para el repositorio después de una actualización gradual.
 a| 
Después de una actualización gradual, actualice la configuración de notificación de resumen para recibir notificaciones.



 a| 
`SMSAP-02076: Label name should not contain any special characters other than underscore.`
 a| 
El nombre de la etiqueta contiene caracteres especiales distintos del guión bajo.
 a| 
El nombre de la etiqueta debe ser único dentro del perfil. El nombre puede contener letras, números, un guión bajo (_) y un guión (-) (pero no puede comenzar con un guión). Asegúrese de que las etiquetas no contengan caracteres especiales excepto el guion bajo.



 a| 
`SMSAP-06308: Exception when attempting to start schedule: java.lang.NullPointerException`
 a| 
Se configura el nombre de dominio completo (FQDN) del host de perfil en lugar del nombre de host del sistema y no se puede resolver el FQDN del host de perfil.
 a| 
Asegúrese de usar el nombre de host del sistema y no el FQDN.



 a| 
`Failure in ExecuteRestoreSteps: ORACLE-10003: Error executing SQL "DROP DISKGROUP;control diskgroup name; INCLUDING CONTENTS" against Oracle database +ASM1: ORA-15039: diskgroup not dropped ORA-15027: active use of diskgroup; "control diskgroup name;" precludes its dismount`
 a| 
La operación para restaurar un backup con archivos de control no puede soltar el grupo de discos de control. Este problema ocurre si hay archivos de control de copia de seguridad obsoletos en el grupo de discos de control.
 a| 
Identifique los archivos de control de copia de seguridad obsoletos y elimínelos manualmente.



 a| 
`RMAN-06004: ORACLE error from recovery catalog database: ORA-01424: missing or illegal character following the escape character`
 a| 
La operación de creación de backup no se pudo quitar la copia de backup del catálogo cuando SnapManager está integrada con RMAN.
 a| 
Compruebe si hay secuencias de comandos externas utilizadas para eliminar las copias de seguridad de RMAN. Ejecute el `*CROSSCHECK BACKUP*` Comando en RMAN para actualizar el repositorio de RMAN y el `*resync catalog*` comando para sincronizar el archivo de control de la base de datos de destino con el catálogo de recuperación.



 a| 
`[DEBUG]: Exception while pruning backup. java.lang.IllegalStateException: [Assertion failed] - this state invariant must be true`
 a| 
Se crean múltiples copias de Snapshot para un solo ID de operación.
 a| 
Eliminar las copias Snapshot manualmente y utilizar scripts para eliminar las entradas del repositorio.



 a| 
La hora y la hora del sistema que muestra SnapManager en los archivos de registro no coinciden o no están sincronizados.
 a| 
Java 7 aún no admite un cambio de zona horaria.
 a| 
Aplique el `tzupdater` Parche suministrado por Oracle.



 a| 
`DISC-00001: Unable to discover storage: The following identifier does not exist or is not of the expected type: ASM File`
 a| 
Los archivos de datos o de control o los redo logs se multiplexan en una base de datos ASM.
 a| 
Extraiga el multiplexado de Oracle.



 a| 
`0001-DS-10021: Unable to set protection policy of dataset <dataset-name> to <new-protection-policy> because the protection policy is already set to <old-protection-policy>. Please use Protection Manager to change the protection policy`
 a| 
Una vez establecida la política de protección de un conjunto de datos, SnapManager no le permitirá cambiar la política de protección, ya que puede requerir volver a alinear las relaciones de base y provocar la pérdida de backups existentes en el almacenamiento secundario.
 a| 
Actualice la política de protección mediante la consola de gestión de Protection Manager, que proporciona más opciones para migrar de una política de protección a otra.



 a| 
`0001-SD-10028: SnapDrive Error (id:2618 code:102) Unable to discover the device associated with "lun_path". If multipathing in use, possible multipathing configuration error. Please verify configuration and retry.`
 a| 
El host no puede detectar las LUN creadas en los sistemas de almacenamiento.
 a| 
Asegúrese de que el protocolo de transporte está correctamente instalado y configurado. Asegúrese de que SnapDrive pueda crear y detectar una LUN en el sistema de almacenamiento.



 a| 
`0001-SD-10028: SnapDrive Error (id:2836 code:110) Failed to acquire dataset lock on volume "storage name":"temp_volume_name"`
 a| 
Se intentó restaurar con el método de almacenamiento indirecto y el volumen temporal especificado no existe en el almacenamiento primario.
 a| 
Cree un volumen temporal en el almacenamiento primario. O bien, especifique el nombre correcto del volumen si ya se ha creado un volumen temporal.



 a| 
`0001-SMSAP-02016: There may have been external tables in the database not backed up as part of this backup operation (since the database was not OPEN during this backup ALL_EXTERNAL_LOCATIONS could not be queried to determine whether or not external tables exist).`
 a| 
SnapManager no realiza copias de seguridad de tablas externas (por ejemplo, tablas que no están almacenadas en archivos .dbf). Este problema se produce porque la base de datos no estaba abierta durante el backup, SnapManager no puede determinar si se están utilizando tablas externas.
 a| 
Puede haber tablas externas en la base de datos que no se incluyeron en un backup como parte de esta operación (porque la base de datos no estaba abierta durante el backup).



 a| 
`0001-SMSAP-11027: Cannot clone or mount snapshots from secondary storage because the snapshots are busy. Try cloning or mounting from an older backup.`
 a| 
Intentó crear una clonación o montar copias Snapshot a partir del almacenamiento secundario del backup protegido más reciente.
 a| 
Clone o monte desde un backup anterior.



 a| 
`0001-SMSAP-12346: Cannot list protection policies because Protection Manager product is not installed or SnapDrive is not configured to use it. Please install Protection Manager and/or configure SnapDrive...`
 a| 
Se intentó enumerar las políticas de protección en un sistema donde SnapDrive no se configuró para usar Protection Manager.
 a| 
Instale Protection Manager y configure SnapDrive para que use Protection Manager.



 a| 
`0001-SMSAP-13032: Cannot perform operation: Backup Delete. Root cause: 0001-SMSAP-02039: Unable to delete backup of dataset: SD-10028: SnapDrive Error (id:2406 code:102) Failed to delete backup id: "backup_id" for dataset, error(23410):Snapshot "snapshot_name" on volume "volume_name" is busy.`
 a| 
Intentó liberar o eliminar el backup protegido más reciente o un backup que contiene copias de Snapshot que son bases de referencia en una relación de mirroring.
 a| 
Libere o elimine el backup protegido.



 a| 
`0002-332 Admin error: Could not check SD.SnapShot.Clone access on volume "volume_name" for user username on Operations Manager server(s) "dfm_server". Reason: Invalid resource specified. Unable to find its ID on Operations Manager server "dfm_server"`
 a| 
No se han configurado los privilegios de acceso adecuados y los roles.
 a| 
Defina los privilegios de acceso o los roles para los usuarios que intentan ejecutar el comando.



 a| 
`[WARN] FLOW-11011: Operation aborted [ERROR] FLOW-11008: Operation failed: Java heap space.`
 a| 
Hay más archivos de registro de archivos en la base de datos que el máximo permitido.
 a| 
. Desplácese hasta el directorio de instalación de SnapManager.
. Abra el `launch-java` archivo.
. Aumente el valor de `java -Xmx160m` Parámetro Java heap space . Por ejemplo, puede modificar el valor del valor predeterminado de 160 m a 200 m. `java -Xmx200m`.




 a| 
`SD-10028: SnapDrive Error (id:2868 code:102) Could not locate remote snapshot or remote qtree.`
 a| 
SnapManager muestra los backups como protegidos aunque el trabajo de protección de Protection Manager solo se haya realizado correctamente parcialmente. Esta condición ocurre cuando la conformidad del conjunto de datos está en curso (cuando las Snapshot básicas se están reflejando).
 a| 
Realizar un nuevo backup tras el conjunto de datos conforme a las exigencias.



 a| 
`SMSAP-21019: The archive log pruning failed for the destination: "/mnt/destination_name/" with the reason: "ORACLE-00101: Error executing RMAN command: [DELETE NOPROMPT ARCHIVELOG '/mnt/destination_name/']`
 a| 
La eliminación del registro de archivo falla en uno de los destinos. En este caso, SnapManager continúa depurando los archivos de registro de archivos de los otros destinos. Si algún archivo se elimina manualmente del sistema de archivos activo, RMAN no puede hacer una copia de los archivos de registro de archivos de ese destino.
 a| 
Conéctese a RMAN desde el host SnapManager. Ejecute RMAN `*CROSSCHECK ARCHIVELOG ALL*` y vuelva a realizar la operación de eliminación en los archivos log de archivos.



 a| 
`SMSAP-13032: Cannot perform operation: Archive log Prune. Root cause: RMAN Exception: ORACLE-00101: Error executing RMAN command.`
 a| 
Los archivos de registro de archivos se eliminan manualmente de los destinos de registro de archivos.
 a| 
Conéctese a RMAN desde el host SnapManager. Ejecute RMAN `*CROSSCHECK ARCHIVELOG ALL*` y vuelva a realizar la operación de eliminación en los archivos log de archivos.



 a| 
`Unable to parse shell output: (java.util.regex.Matcher[pattern=Command complete. region=0,18 lastmatch=]) does not match (name:backup_script)`

`Unable to parse shell output: (java.util.regex.Matcher[pattern=Command complete. region=0,25 lastmatch=]) does not match (description:backup script)`

`Unable to parse shell output: (java.util.regex.Matcher[pattern=Command complete. region=0,9 lastmatch=]) does not match (timeout:0)`
 a| 
Las variables de entorno no se definen correctamente en los scripts previos o posteriores a las tareas.
 a| 
Compruebe si las secuencias de comandos previas o posteriores a las tareas siguen la estructura del complemento SnapManager estándar. Para obtener información adicional sobre el uso de las variables de entorno en el script, consulte xref:concept-operations-in-task-scripts.adoc[Operaciones en scripts de tareas].



 a| 
`ORA-01450: maximum key length (6398) exceeded.`
 a| 
Cuando se realiza una actualización de SnapManager 3.2 para SAP a SnapManager 3.3 para SAP, la operación de actualización genera este mensaje de error. Este problema puede ocurrir debido a uno de los siguientes motivos:

* El tamaño de bloque del tablespace en el que existe el repositorio es inferior a 8k.
* La `nls_length_semantics` el parámetro se establece en char.

 a| 
Debe asignar los valores a los siguientes parámetros:

* `block_size=*8192*`
* `nls_length=*byte*`


Después de modificar los valores de los parámetros, debe reiniciar la base de datos.

Para obtener más información, consulte el artículo 2017632 de la base de conocimientos.

|===


== Mensajes de error asociados con el proceso de copia de seguridad de la base de datos (serie 2000)

En la siguiente tabla se enumeran los errores comunes asociados al proceso de copia de seguridad de la base de datos:

[cols="1a,1a,1a"]
|===
| Mensaje de error | Explicación | Resolución 


 a| 
`SMSAP-02066: You cannot delete or free the archive log backup "data-logs" as the backup is associated with data backup "data-logs".`
 a| 
La copia de seguridad del registro de archivos se realiza junto con la copia de seguridad de los archivos de datos y se intentó eliminar el backup del registro de archivos.
 a| 
Utilice la `_-force_` opción para eliminar o liberar el backup.



 a| 
`SMSAP-02067: You cannot delete, or free the archive log backup "data-logs" as the backup is associated with data backup "data-logs" and is within the assigned retention duration.`
 a| 
El backup de registros de archivos se asocia con el backup de la base de datos y se encuentra dentro del período de retención, y se intentó eliminar el backup de registros de archivos.
 a| 
Utilice la `_-force_` opción para eliminar o liberar el backup.



 a| 
`SMSAP-07142: Archived Logs excluded due to exclusion pattern <exclusion> pattern.`
 a| 
Se excluyen algunos archivos de registro de archivos durante la operación de creación de perfiles o creación de copias de seguridad.
 a| 
No se requiere ninguna acción.



 a| 
`SMSAP-07155: <count> archived log files do not exist in the active file system. These archived log files will not be included in the backup.`
 a| 
Los archivos de registro de archivos no existen en el sistema de archivos activo durante la operación de creación de perfiles o de creación de backup. Estos archivos de registro archivados no se incluyen en la copia de seguridad.
 a| 
No se requiere ninguna acción.



 a| 
`SMSAP-07148: Archived log files are not available.`
 a| 
No se crean archivos de registro de archivos para la base de datos actual durante la operación de creación de perfiles o creación de backups.
 a| 
No se requiere ninguna acción.



 a| 
`SMSAP-07150: Archived log files are not found.`
 a| 
Faltan todos los archivos de registro de archivos del sistema de archivos o se excluyen durante la operación de creación de perfiles o creación de copia de seguridad.
 a| 
No se requiere ninguna acción.



 a| 
`SMSAP-13032: Cannot perform operation: Backup Create. Root cause: ORACLE-20001: Error trying to change state to OPEN for database instance dfcln1: ORACLE-20004: Expecting to be able to open the database without the RESETLOGS option, but oracle is reporting that the database needs to be opened with the RESETLOGS option. To keep from unexpectedly resetting the logs, the process will not continue. Please ensure that the database can be opened without the RESETLOGS option and try again.`
 a| 
Se intenta realizar una copia de seguridad de la base de datos clonada que se creó con la opción -no-resetlogs. La base de datos clonada no es una base de datos completa. Sin embargo, es posible realizar operaciones de SnapManager, como crear perfiles y backups, dividir clones, etc. con la base de datos clonada, pero se produce un error en las operaciones de SnapManager debido a que la base de datos clonada no se configura como una base de datos completa.
 a| 
Recuperar la base de datos clonada o convertir la base de datos a una base de datos de Data Guard en espera.

|===


== Errores de protección de datos

En la siguiente tabla se muestran los errores comunes asociados con la protección de datos:

[cols="1a,1a,1a"]
|===
| Mensaje de error | Explicación | Resolución 


 a| 
`Backup protection is requested but the database profile does not have a protection policy. Please update the protection policy in the database profile or do not use the 'protect' option when creating backups.`
 a| 
Se intenta crear un backup con protección en el almacenamiento secundario; sin embargo, el perfil asociado a este backup no tiene una política de protección especificada.
 a| 
Edite el perfil y seleccione una política de protección. Vuelva a crear el backup.



 a| 
`Cannot delete profile because data protection is enabled but the Protection Manager is temporarily unavailable. Please try again later.`
 a| 
Se intenta eliminar un perfil que tiene la protección habilitada; sin embargo, Protection Manager no está disponible.
 a| 
Asegúrese de que los backups adecuados se almacenen en el almacenamiento primario o secundario. Desactive la protección en el perfil. Cuando Protection Manager esté disponible de nuevo, vuelva al perfil y elimínelo.



 a| 
`Cannot list protection policies because Protection Manager is temporarily unavailable. Please try again later.`
 a| 
Al configurar el perfil de backup, debe habilitar la protección en el backup para que el backup se almacene en el almacenamiento secundario. Sin embargo, SnapManager no puede recuperar las políticas de protección de la consola de gestión de Protection Manager.
 a| 
Desactive la protección en el perfil temporalmente. Continúe creando un nuevo perfil o actualizando un perfil existente. Cuando Protection Manager esté disponible de nuevo, vuelva al perfil.



 a| 
`Cannot list protection policies because Protection Manager product is not installed or SnapDrive is not configured to use it. Please install Protection Manager and/or configure SnapDrive.`
 a| 
Al configurar el perfil de backup, debe habilitar la protección en el backup para que el backup se almacene en el almacenamiento secundario. Sin embargo, SnapManager no puede recuperar las políticas de protección de la Consola de gestión de Protection Manager. Protection Manager no está instalado o SnapDrive no está configurado.
 a| 
Instale Protection Manager. Configure SnapDrive.

Vuelva al perfil, vuelva a activar la protección y seleccione las políticas de protección disponibles en la consola de gestión de Protection Manager.



 a| 
`Cannot set protection policy because Protection Manager is temporarily unavailable. Please try again later.`
 a| 
Al configurar el perfil de backup, debe habilitar la protección en el backup para que el backup se almacene en el almacenamiento secundario. Sin embargo, SnapManager no puede recuperar las políticas de protección de la Consola de gestión de Protection Manager.
 a| 
Desactive la protección en el perfil temporalmente. Continúe creando o actualizando el perfil. Cuando la Consola de administración de Protection Manager esté disponible, vuelva al perfil.



 a| 
`Creating new dataset <dataset_name> for database <dbname> on host <host>.`
 a| 
Ha intentado crear un perfil de copia de seguridad. SnapManager crea un conjunto de datos para este perfil.
 a| 
No es necesario realizar ninguna acción.



 a| 
`Data protection is not available because Protection Manager is not installed.`
 a| 
Al configurar el perfil de backup, se intentó habilitar la protección en el backup para que el backup se almacenara en el almacenamiento secundario. Sin embargo, SnapManager no puede acceder a las políticas de protección desde la consola de gestión de Protection Manager. Protection Manager no está instalado.
 a| 
Instale Protection Manager.



 a| 
`Deleted dataset <dataset_name> for this database.`
 a| 
Ha eliminado un perfil. SnapManager eliminará el conjunto de datos asociado.
 a| 
No es necesario realizar ninguna acción.



 a| 
`Deleting profile with protection enabled and Protection Manager is no longer configured. Deleting profile from SnapManager but not cleaning up dataset in Protection Manager.`
 a| 
Se intentó eliminar un perfil que tiene la protección habilitada; sin embargo, Protection Manager ya no está instalado o ya no está configurado o ha caducado. SnapManager eliminará el perfil, pero no el conjunto de datos del perfil de la consola de gestión de Protection Manager.
 a| 
Vuelva a instalar o vuelva a configurar Protection Manager. Vuelva al perfil y elimínelo.



 a| 
`Invalid retention class. Use "smsap help backup" to see a list of available retention classes.`
 a| 
Al configurar la directiva de retención, intentó utilizar una clase de retención no válida.
 a| 
Cree una lista de clases de retención válidas introduciendo este comando: `*smsap help backup*`

Actualice la directiva de retención con una de las clases disponibles.



 a| 
`Specified protection policy is not available. Use "smsap protection-policy list" to see a list of available protection policies.`
 a| 
Al configurar el perfil, debe habilitar la protección e introducir una política de protección que no esté disponible.
 a| 
Identifique las políticas de protección disponibles con el siguiente comando: `*smsap protection-policy list*`



 a| 
`Using existing dataset <dataset_name> for database <dbname> on host <host> since the dataset already existed.`
 a| 
Intentó crear un perfil; sin embargo, el conjunto de datos para el mismo perfil de base de datos ya existe.
 a| 
Compruebe las opciones del perfil existente y asegúrese de que coinciden con lo que necesita en el nuevo perfil.



 a| 
`Using existing dataset <dataset_name> for RAC database <dbname> since profile <profile_name> for the same RAC database already exists for instance <SID> on host <hostname>.`
 a| 
Intentó crear un perfil para una base de datos RAC; sin embargo, el conjunto de datos para el mismo perfil de base de datos RAC ya existe.
 a| 
Compruebe las opciones del perfil existente y asegúrese de que coinciden con lo que necesita en el nuevo perfil.



 a| 
`The dataset <dataset_name> with protection policy <existing_policy_name> already exists for this database. You have specified protection policy <new_policy_name>. The dataset's protection policy will be changed to <new_policy_name>. You can change the protection policy by updating the profile.`
 a| 
Ha intentado crear un perfil con la protección activada y una política de protección seleccionada. Sin embargo, el conjunto de datos para el mismo perfil de base de datos ya existe, pero tiene una política de protección diferente. SnapManager usará la política recién especificada para el conjunto de datos existente.
 a| 
Revise esta política de protección y determine si esta es la política que desea usar para el conjunto de datos. Si no es así, edite el perfil y cambie la directiva.



 a| 
`Protection Manager deletes the local backups created by SnapManager for SAP`
 a| 
La consola de gestión de Protection Manager elimina o libera los backups locales creados por SnapManager de acuerdo con la política de retención definida en Protection Manager. La clase de retención establecida para los backups locales no se considera mientras se eliminan o liberan los backups locales.cuando los backups locales se transfieren a un sistema de almacenamiento secundario, no se considera la clase de retención establecida para los backups locales en el sistema de almacenamiento primario. La clase de retención especificada en el programa de transferencia se asigna a la copia de seguridad remota.
 a| 
Ejecute el `dfpm dataset fix_smsap` Comando del servidor de Protection Manager cada vez que se crea un nuevo conjunto de datos.ahora los backups no se eliminan de acuerdo con la normativa de retención definida en la consola de gestión de Protection Manager.



 a| 
`You have selected to disable protection for this profile. This could potentially delete the associated dataset in Protection Manager and destroy the replication relationships created for that dataset. You will also not be able to perform SnapManager operations such as restoring or cloning the secondary or tertiary backups for this profile. Do you wish to continue (Y/N)?`
 a| 
Intentó deshabilitar la protección para un perfil protegido al actualizar el perfil desde la interfaz gráfica de usuario o la interfaz de línea de comandos de SnapManager. Puede desactivar la protección para el perfil mediante `-noprotect` Opción de la CLI de SnapManager o desactive la casilla de verificación *Directiva de protección de Protection Manager* de la ventana Propiedades de directivas de la GUI de SnapManager. Cuando se deshabilita la protección para el perfil, SnapManager para SAP elimina el conjunto de datos de la consola de gestión de Protection Manager, que cancela el registro de todas las copias de backup secundarias y terciarias asociadas con ese conjunto de datos.

Tras eliminar un conjunto de datos, todas las copias de backup secundarias y terciarias se huérfanas. Ni Protection Manager ni SnapManager para SAP tienen la capacidad de acceder a esas copias de backup. Ya no es posible restaurar las copias de backup mediante SnapManager para SAP.


NOTE: Se muestra el mismo mensaje de advertencia incluso cuando el perfil no está protegido.
 a| 
Este es un problema conocido en SnapManager para SAP y el comportamiento esperado dentro de Protection Manager al destruir un conjunto de datos. No existe ninguna solución alternativa.los backups huérfanos deben gestionarse manualmente.

|===


== Mensajes de error asociados con el proceso de restauración (serie 3000)

En la siguiente tabla se muestran los errores comunes asociados con el proceso de restauración:

[cols="1a,1a,1a"]
|===
| Mensaje de error | Explicación | Resolución 


 a| 
`SMSAP-03031:Restore specification is required to restore backup <variable> because the storage resources for the backup has already been freed.`
 a| 
Intentó restaurar una copia de seguridad que tiene liberados sus recursos de almacenamiento sin especificar una especificación de restauración.
 a| 
Especifique una especificación de restauración.



 a| 
`SMSAP-03032:Restore specification must contain mappings for the files to restore because the storage resources for the backup has already been freed. The files that need mappings are: <variable> from Snapshots: <variable>`
 a| 
Intentó restaurar una copia de seguridad que tiene liberados sus recursos de almacenamiento junto con una especificación de restauración que no contiene la asignación de todos los archivos que se van a restaurar.
 a| 
Corrija el archivo de especificación de restauración de modo que las asignaciones coincidan con los archivos que se van a restaurar.



 a| 
`ORACLE-30028: Unable to dump log file <filename>. The file may be missing/inaccessible/corrupted. This log file will not be used for recovery.`
 a| 
Los archivos redo log en línea o los archivos archive log no se pueden utilizar para la recuperación.este error se produce debido a los siguientes motivos:

* Los archivos redo log en línea o los archivos archive log mencionados en el mensaje de error no tienen números de cambio suficientes para solicitar la recuperación. Esto ocurre cuando la base de datos está en línea sin ninguna transacción. Los archivos redo log o archive log no tienen ningún número de cambio válido que se pueda aplicar para la recuperación.
* El archivo redo log en línea o el archivo archive log mencionado en el mensaje de error no tiene suficientes privilegios de acceso para Oracle.
* El archivo redo log en línea o el archivo de registro archivado mencionado en el mensaje de error están dañados y Oracle no puede leerlos.
* El archivo redo log en línea o el archivo de registro archivado mencionado en el mensaje de error no se encuentra en la ruta de acceso mencionada.

 a| 
Si el archivo mencionado en el mensaje de error es un archivo de registro archivado y si ha proporcionado manualmente para la recuperación, asegúrese de que el archivo tiene permisos de acceso completo a Oracle.incluso si el archivo tiene permisos completos, y el mensaje continúa, el archivo de registro de archivo no tiene ningún número de cambio que se aplicará para la recuperación, y este mensaje puede ignorarse.



 a| 
`SMSAP-03038: Cannot restore from secondary because the storage resources still exist on primary. Please restore from primary instead.`
 a| 
Intentó restaurar desde el almacenamiento secundario, pero existen copias Snapshot en el almacenamiento primario.
 a| 
Restaure siempre desde el principal si el backup no se ha liberado.



 a| 
`SMSAP-03054: Mounting backup archbkp1 to feed archivelogs. DS-10001: Connecting mountpoints. [ERROR] FLOW-11019: Failure in ExecuteConnectionSteps: SD-10028: SnapDrive Error (id:2618 code:305). The following files could not be deleted. The corresponding volumes might be read-only. Retry the command with older snapshots.[ERROR] FLOW-11010: Operation transitioning to abort due to prior failure.`
 a| 
Durante la recuperación, SnapManager intenta montar el backup más reciente del sistema secundario para alimentar los archivos de registro de archivos desde el secundario. Sin embargo, si hay otros backups, la recuperación puede tener éxito. Sin embargo, si no hay otros backups, es posible que se produzca un error en la recuperación.
 a| 
No elimine los backups más recientes del almacenamiento primario, por lo que SnapManager puede utilizar el backup principal para la recuperación.

|===


== Mensajes de error asociados con el proceso de clonación (serie 4000)

En la siguiente tabla se muestran los errores comunes asociados con el proceso de clonación:

[cols="1a,1a,1a"]
|===
| Mensaje de error | Explicación | Resolución 


 a| 
`SMSAP-04133: Dump destination must not exist`
 a| 
Se está utilizando SnapManager para crear nuevos clones; sin embargo, los destinos de volcado que usará el nuevo clon ya existen. SnapManager no puede crear un clon si existen destinos de volcado.
 a| 
Quite o cambie el nombre de los destinos de volcado antiguos antes de crear un clon.



 a| 
`SMSAP-04908: Not a FlexClone.`
 a| 
El clon es un clon LUN. Esto se aplica tanto a Data ONTAP 8.1 7-Mode como a Clustered Data ONTAP.
 a| 
SnapManager admite la división de clones únicamente en la tecnología FlexClone.



 a| 
`SMSAP-04904: No clone split operation running with _split-idsplit_id_`
 a| 
El ID de la operación no es válido o no hay ninguna operación de división de clones en curso.
 a| 
Proporcione un ID de división o una etiqueta de división válidos para el estado de división de clones, resultados y operaciones de detención.



 a| 
`SMSAP-04906: Stop clone split operation failed with _split-idsplit_id_`
 a| 
Se ha completado la operación de división.
 a| 
Compruebe si el proceso de división está en curso utilizando `*clone split-status*` o. `*clone split-result*` comando.



 a| 
`SMSAP-13032:Cannot perform operation: Clone Create. Root cause: ORACLE-00001: Error executing SQL: [ALTER DATABASE OPEN RESETLOGS;]. The command returned: ORA-38856: cannot mark instance UNNAMED_INSTANCE_2 (redo thread 2) as enabled.`
 a| 
Se produce un error en la creación del clon cuando se crea desde la base de datos en espera con la siguiente configuración:

* La base de datos primaria es una configuración de RAC y la base de datos en espera es independiente.
* El modo de espera se crea mediante RMAN para realizar una copia de seguridad de los archivos de datos.

 a| 
Añada el `_no_recovery_through_resetlogs=TRUE` parámetro en el archivo de especificación del clon antes de crear el clon. Consulte la documentación de Oracle (ID 334899.1) para obtener información adicional. Asegúrese de tener el nombre de usuario y la contraseña de Oracle metalink.



 a| 
`[INFO] Operation failed. Syntax errors in clone specification: [error: cvc-complex-type.2.4c: Expected elements 'value@http://www.example.com default@http://www.example.com' before the end of the content in element parameter@http://www.example.com]`
 a| 
No ha especificado un valor para un parámetro en el archivo de especificación del clon.
 a| 
Debe proporcionar un valor para el parámetro o eliminar ese parámetro si no es necesario en el archivo de especificación del clon.

|===


== Mensajes de error asociados con el proceso de gestión de perfiles (serie 5000)

En la siguiente tabla se muestran los errores comunes asociados con el proceso de clonación:

[cols="1a,1a,1a"]
|===
| Mensaje de error | Explicación | Resolución 


 a| 
`SMSAP-20600: Profile "profile1" not found in repository "repo_name". Please run "profile sync" to update your profile-to-repository mappings.`
 a| 
La operación de volcado no se puede realizar cuando se produce un error al crear el perfil.
 a| 
Uso `smsapsystem dump`.

|===


== Mensajes de error asociados con la liberación de recursos de backup (series de backups 6000)

En la siguiente tabla se muestran los errores comunes asociados con las tareas de backup:

[cols="1a,1a,1a"]
|===
| Mensaje de error | Explicación | Resolución 


 a| 
`SMSAP-06030: Cannot remove backup because it is in use: <variable>`
 a| 
Se intentó realizar la operación de backup libre con comandos, cuando el backup se monta o se Marca que se retiene de forma ilimitada.
 a| 
Desmonte el backup o cambie la política de retención ilimitada. Si hay clones, elimínelos.



 a| 
`SMSAP-06045: Cannot free backup <variable> because the storage resources for the backup have already been freed`
 a| 
Se intentó realizar la operación de backup libre con comandos, cuando ya se ha liberado el backup.
 a| 
No se puede liberar la copia de seguridad si ya se ha liberado.



 a| 
`SMSAP-06047: Only successful backups can be freed. The status of backup <ID> is <status>.`
 a| 
Se intentó realizar la operación de backup libre con comandos, cuando el estado del backup no es correcto.
 a| 
Vuelva a intentarlo después de realizar el backup correctamente.



 a| 
`SMSAP-13082: Cannot perform operation <variable> on backup <ID> because the storage resources for the backup have been freed.`
 a| 
Con comandos, se intentó montar un backup con los recursos de almacenamiento liberados.
 a| 
No se pueden montar, clonar, verificar ni ejecutar restauraciones backint en un backup que tenga liberados los recursos de almacenamiento.

|===


== Errores de interfaz de almacenamiento virtual (serie 8000 de interfaz de almacenamiento virtual)

La siguiente tabla muestra los errores comunes asociados con las tareas de interfaz de almacenamiento virtual:

[cols="1a,1a,1a"]
|===
| Mensaje de error | Explicación | Resolución 


 a| 
`SMSAP-08017 Error discovering storage for /.`
 a| 
SnapManager intentó localizar recursos de almacenamiento, pero encontró archivos de datos, archivos de control o registros en el `root/` directorio. Estos archivos deben residir en un subdirectorio. El sistema de archivos raíz puede ser un disco duro en su equipo local. SnapDrive no puede hacer copias snapshot en esta ubicación y SnapManager no puede realizar operaciones con estos archivos.
 a| 
Compruebe si los archivos de datos, los archivos de control o los registros de recuperación están en la `root` directorio. Si es así, muévalos a sus ubicaciones correctas o vuelva a crear archivos de control o redo logs en sus ubicaciones correctas. El punto de montaje básico es siempre

* `/oracle/<SID>` En entornos basados en UNIX
* `[drive:]\oracle\<SID>` En entornos basados en Windows


SAP utiliza cuatro grupos de redo log con dos miembros:

* Un miembro se almacena en origlog{A|B}.
* El otro miembro se refleja en Mirrlog{A|B}.


|===


== Mensajes de error asociados con el proceso de actualización gradual (serie 9000)

En la siguiente tabla se muestran los errores comunes asociados con el proceso de actualización gradual:

[cols="1a,1a,1a"]
|===
| Mensaje de error | Explicación | Resolución 


 a| 
`SMSAP-09234:Following hosts does not exist in the old repository. <hostnames>.`
 a| 
Intentó realizar una actualización gradual de un host, que no existe en la versión de repositorio anterior.
 a| 
Compruebe si el host existe en el repositorio anterior mediante el `repository show-repository` Comando desde la versión anterior de la interfaz de línea de comandos de SnapManager.



 a| 
`SMSAP-09255:Following hosts does not exist in the new repository. <hostnames>.`
 a| 
Intentó realizar la reversión de un host, que no existe en la versión del nuevo repositorio.
 a| 
Compruebe si el host existe en el nuevo repositorio mediante el `repository show-repository` Comando desde la versión posterior de la CLI de SnapManager.



 a| 
`SMSAP-09256:Rollback not supported, since there exists new profiles <profilenames>.for the specified hosts <hostnames>.`
 a| 
Intentó revertir un host que contiene nuevos perfiles existentes en el repositorio. Sin embargo, estos perfiles no existían en el host de la versión anterior de SnapManager.
 a| 
Elimine nuevos perfiles en la versión posterior o actualizada de SnapManager antes de la reversión.



 a| 
`SMSAP-09257:Rollback not supported, since the backups <backupid> are mounted in the new hosts.`
 a| 
Intentó revertir una versión posterior del host SnapManager que tiene backups montados. Estos backups no se montan en la versión anterior del host SnapManager.
 a| 
Desmonte los backups en la versión posterior del host SnapManager y, a continuación, realice la reversión.



 a| 
`SMSAP-09258:Rollback not supported, since the backups <backupid> are unmounted in the new hosts.`
 a| 
Ha intentado revertir una versión posterior del host SnapManager que tiene backups que se están desdesmontan.
 a| 
Monte los backups en la versión posterior del host SnapManager y, a continuación, ejecute la reversión.



 a| 
`SMSAP-09298:Cannot update this repository since it already has other hosts in the higher version. Please perform rollingupgrade for all hosts instead.`
 a| 
Realizó una actualización gradual en un solo host y, después, actualizó el repositorio para ese host.
 a| 
Realice una actualización gradual en todos los hosts.



 a| 
`SMSAP-09297: Error occurred while enabling constraints. The repository might be in inconsistent state. It is recommended to restore the backup of repository you have taken before the current operation.`
 a| 
Se intentó realizar una operación de reversión o actualización sucesiva si la base de datos del repositorio queda en estado incoherente.
 a| 
Restaurar el repositorio del que se ha hecho backup anteriormente.

|===


== Ejecución de operaciones (serie 12,000)

En la siguiente tabla se muestran los errores comunes asociados a las operaciones:

[cols="1a,1a,1a"]
|===
| Mensaje de error | Explicación | Resolución 


 a| 
`SMSAP-12347 [ERROR]: SnapManager server not running on host <host> and port <port>. Please run this command on a host running the SnapManager server.`
 a| 
Al configurar el perfil, debe introducir información sobre el host y el puerto. Sin embargo, SnapManager no puede realizar estas operaciones porque el servidor SnapManager no está en ejecución en el host y el puerto especificados.
 a| 
Introduzca el comando en un host que ejecuta el servidor SnapManager. Puede comprobar el puerto con el `lsnrctl status` y vea el puerto en el que se ejecuta la base de datos. Si es necesario, cambie el puerto del comando backup.

|===


== Ejecución de componentes de proceso (serie 13,000)

En la siguiente tabla se muestran los errores comunes asociados con el componente de proceso de SnapManager:

[cols="1a,1a,1a"]
|===
| Mensaje de error | Explicación | Resolución 


 a| 
`SMSAP-13083: Snapname pattern with value "x" contains characters other than letters, numbers, underscore, dash, and curly braces.`
 a| 
Al crear un perfil, ha personalizado el patrón de Snapname; sin embargo, ha incluido caracteres especiales que no están permitidos.
 a| 
Quite caracteres especiales que no sean letras, números, guion bajo, guion y corchetes.



 a| 
`SMSAP-13084: Snapname pattern with value "x" does not contain the same number of left and right braces.`
 a| 
Al crear un perfil, ha personalizado el patrón de Snapname; sin embargo, las llaves izquierda y derecha no coinciden.
 a| 
Introduzca los corchetes de apertura y cierre coincidentes en el patrón de Snapname.



 a| 
`SMSAP-13085: Snapname pattern with value "x" contains an invalid variable name of "y".`
 a| 
Al crear un perfil, ha personalizado el patrón de Snapname; sin embargo, ha incluido una variable que no está permitida.
 a| 
Elimine la variable ofensor. Para ver una lista de variables aceptables, consulte xref:concept-snapshot-copy-naming.adoc[Nomenclatura de copias Snapshot].



 a| 
`SMSAP-13086 Snapname pattern with value "x" must contain variable "smid".`
 a| 
Al crear un perfil, ha personalizado el patrón de Snapname; sin embargo, ha omitido el requerido `_smid_` variable.
 a| 
Inserte el necesario `_smid_` variable.



 a| 
`SMSAP-13902: Clone Split Start failed.`
 a| 
Puede haber varios motivos para este error:

* No hay espacio en el volumen.
* SnapDrive no está en ejecución.
* El clon puede ser un clon de la LUN.
* El volumen de FlexVol tiene copias snapshot restringidas.

 a| 
Compruebe el espacio disponible en el volumen mediante el `*clone split-estimate*` comando. Confirmar que el volumen FlexVol no tiene copias snapshot restringidas.



 a| 
`SMSAP-13904: Clone Split Result failed.`
 a| 
Esto podría deberse a un fallo en el SnapDrive o el sistema de almacenamiento.
 a| 
Intente trabajar con un clon nuevo.



 a| 
`SMSAP-13906: Split operation already running for clone label _clone-label_ or ID _clone-id_.`
 a| 
Intenta dividir un clon que ya está dividido.
 a| 
El clon ya está dividido y se eliminarán los metadatos relacionados con los clones.



 a| 
`SMSAP-13907: Split operation already running for clone label _clone-label_ or ID _clone-id_`.
 a| 
Está intentando dividir un clon que está en proceso de división.
 a| 
Debe esperar hasta que finalice la operación de división.

|===


== Mensajes de error asociados con utilidades de SnapManager (serie 14,000)

En la siguiente tabla se muestran los errores comunes asociados con las utilidades de SnapManager:

[cols="1a,1a,1a"]
|===
| Mensaje de error | Explicación | Resolución 


 a| 
`SMSAP-14501: Mail ID cannot be blank.`
 a| 
No ha introducido la dirección de correo electrónico.
 a| 
Introduzca una dirección de correo electrónico válida.



 a| 
`SMSAP-14502: Mail subject cannot be blank.`
 a| 
No ha introducido el asunto del correo electrónico.
 a| 
Introduzca el asunto del correo electrónico que corresponda.



 a| 
`SMSAP-14506: Mail server field cannot be blank.`
 a| 
No se introdujo el nombre de host ni la dirección IP del servidor de correo electrónico.
 a| 
Introduzca el nombre de host o la dirección IP del servidor de correo válido.



 a| 
`SMSAP-14507: Mail Port field cannot be blank.`
 a| 
No ha introducido el número de puerto de correo electrónico.
 a| 
Introduzca el número de puerto del servidor de correo electrónico.



 a| 
`SMSAP-14508: From Mail ID cannot be blank.`
 a| 
No ha introducido la dirección de correo electrónico del remitente.
 a| 
Introduzca una dirección de correo electrónico del remitente válida.



 a| 
`SMSAP-14509: Username cannot be blank.`
 a| 
Habilitó la autenticación y no proporcionó el nombre de usuario.
 a| 
Introduzca el nombre de usuario de autenticación por correo electrónico.



 a| 
`SMSAP-14510: Password cannot be blank. Please enter the password.`
 a| 
Habilitó la autenticación y no proporcionó la contraseña.
 a| 
Introduzca la contraseña de autenticación por correo electrónico.



 a| 
`SMSAP-14550: Email status <success/failure>.`
 a| 
El número de puerto, el servidor de correo o la dirección de correo electrónico del receptor no son válidos.
 a| 
Proporcione los valores adecuados durante la configuración del correo electrónico.



 a| 
`SMSAP-14559: Sending email notification failed: <error>.`
 a| 
Esto podría deberse a un número de puerto no válido, a un servidor de correo no válido o a una dirección de correo del destinatario no válida.
 a| 
Proporcione los valores adecuados durante la configuración del correo electrónico.



 a| 
`SMSAP-14560: Notification failed: Notification configuration is not available.`
 a| 
Error en el envío de notificaciones porque la configuración de notificación no está disponible.
 a| 
Agregar configuración de notificación.



 a| 
`SMSAP-14565: Invalid time format. Please enter time format in HH:mm.`
 a| 
Introdujo la hora en un formato incorrecto.
 a| 
Introduzca la hora en el formato: hh:mm.



 a| 
`SMSAP-14566: Invalid date value. Valid date range is 1-31.`
 a| 
La fecha configurada es incorrecta.
 a| 
La fecha debe estar entre 1 y 31.



 a| 
`SMSAP-14567: Invalid day value. Valid day range is 1-7.`
 a| 
El día configurado es incorrecto.
 a| 
Introduzca el intervalo de días del 1 al 7.



 a| 
`SMSAP-14569: Server failed to start Summary Notification schedule.`
 a| 
El servidor SnapManager se cerró por motivos desconocidos.
 a| 
Inicie el servidor SnapManager.



 a| 
`SMSAP-14570: Summary Notification not available.`
 a| 
No ha configurado la notificación de resumen.
 a| 
Configure la notificación de resumen.



 a| 
`SMSAP-14571: Both profile and summary notification cannot be enable.`
 a| 
Ha seleccionado las opciones de notificación de perfil y resumen.
 a| 
Habilite la notificación de perfil o la notificación de resumen.



 a| 
`SMSAP-14572: Provide success or failure option for notification.`
 a| 
No ha habilitado las opciones de éxito o fallo.
 a| 
Debe seleccionar Success o Failure Option o both.

|===


== Mensajes de error comunes de SnapDrive para UNIX

En la siguiente tabla se muestran los errores comunes relacionados con SnapDrive para UNIX:

[cols="1a,1a"]
|===
| Mensaje de error | Explicación 


 a| 
`0001-136 Admin error: Unable to log on to filer: <filer> Please set user name and/or password for <filer>`
 a| 
Error de configuración inicial



 a| 
`0001-382 Admin error: Multipathing rescan failed`
 a| 
Error de detección de LUN



 a| 
`0001-462 Admin error: Failed to unconfigure multipathing for <LUN>: spd5: cannot stop device. Device busy.`
 a| 
Error de detección de LUN



 a| 
`0001-476 Admin error: Unable to discover the device associated with...`
 a| 
Error de detección de LUN



 a| 
`0001-680 Admin error: Host OS requires an update to internal data to allow LUN creation or connection. Use 'snapdrive config prepare luns' or update this information manually...`
 a| 
Error de detección de LUN



 a| 
`0001-710 Admin error: OS refresh of LUN failed...`
 a| 
Error de detección de LUN



 a| 
`0001-817 Admin error: Failed to create volume clone... : FlexClone not licensed`
 a| 
Error de configuración inicial



 a| 
`0001-817 Admin error: Failed to create volume clone... : Request failed as space cannot be guaranteed for the clone`.
 a| 
Problema de espacio



 a| 
`0001-878 Admin error: HBA assistant not found. Commands involving LUNs should fail.`
 a| 
Error de detección de LUN



 a| 
`SMSAP-12111: Error executing snapdrive command "<snapdrive command>": <snapdrive error>`
 a| 
Error genérico de SnapDrive para UNIX

|===