---
permalink: unix-administration/task-split-a-clone-on-a-primary-or-secondary-storage.html 
sidebar: sidebar 
keywords: clone, split, complete, metadata, remove, repository, primary, secondary, storage, delete, free 
summary: Puede usar el comando clone split para dividir el clon. Una vez finalizada la división de clones, los metadatos del clon se eliminan de la base de datos del repositorio y es posible eliminar o liberar el backup asociado con el clon. 
---
= Divida un clon en el almacenamiento primario o secundario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `clone split` comando para dividir el clon. Una vez finalizada la división de clones, los metadatos del clon se eliminan de la base de datos del repositorio y es posible eliminar o liberar el backup asociado con el clon.

*Acerca de esta tarea*

El nuevo perfil creado después de la operación de división correcta se utiliza para gestionar el clon de división. El nuevo perfil será como cualquier otro perfil existente en SnapManager. Este perfil se puede usar para llevar a cabo operaciones de backup, restauración y clonado.

Además, también es posible configurar las notificaciones por correo electrónico para el nuevo perfil. Esto permite al administrador de la base de datos recibir notificaciones sobre el estado de la operación de la base de datos realizada mediante el perfil.


NOTE: SnapManager admite la operación de separación cuando se realiza únicamente en FlexClone.

Si la operación de división falla, se muestra un mensaje de error adecuado con el motivo del fallo. El estado de varias operaciones también se muestra en el registro de operaciones. Por ejemplo:

[listing]
----
--[ INFO] The following operations were completed:
Clone Split : Success
Profile Create : Failed
Clone Detach : Success
----
Opcionalmente, es posible recoger los archivos de volcado después de una operación de división de clones realizada correctamente o con errores.


NOTE: Después de introducir el `clone split` No debe detener el servidor SnapManager hasta que se haya iniciado la operación de división de clones.


NOTE: SnapManager genera el perfil aunque no proporcione ningún valor para la cuenta de Oracle (osaccount y osgroup).

.Paso
. Introduzca el siguiente comando:
+
`*smsap clone split -profile _clone-profile_ -host _hostname_ [-label _clone-label_ | -id _clone-id_]-split-label _split-operation-label_ -comment _comment_ new-profile _new-profile-name_ [-profile-password _new-profile_password_] -repository -dbname _repo_service_name_ -host _repo_host_ -port _repo_port_ -login-username _repo_username_ -database -dbname _db_dbname_ -host _db_host_ [-siddb_sid] [-login-username _db_username_ -password _db_password_ -port _db_port_] [-rman {-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_} } ] -osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly-count _n_] [-duration _m_]] [-daily-count _n_] [-duration _m_]] [-weekly-count _n_] [-duration _m_]] [-monthly-count _n_] [-duration _m_]]] [-profile-comment _profile-comment_][-snapname-pattern _pattern_][-protect [-protection-policy _policy_name_]] | [-noprotect]][-summary-notification] [-notification [-success-email _email_address1, email_address2_ -subject _subject_pattern_] [-failure-email _email_address1, email_address2_ -subject _subject_pattern_]][-quiet | -verbose]-dump*`


