---
permalink: unix-administration/task-authorize-user-access-to-the-repository.html 
sidebar: sidebar 
keywords: addition, role-based, access, control, rbac, snapmanager, enable, set, credential, database, repository, restrict, prevent, host, profile, database, authorizing, authorize 
summary: 'Adem치s del control de acceso basado en roles (RBAC), SnapManager permite configurar credenciales para que los usuarios de la base de datos accedan al repositorio. Con las credenciales, puede restringir o evitar el acceso a hosts, repositorios, perfiles y bases de datos de SnapManager.' 
---
= Autorizar el acceso al repositorio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Adem치s del control de acceso basado en roles (RBAC), SnapManager permite configurar credenciales para que los usuarios de la base de datos accedan al repositorio. Con las credenciales, puede restringir o evitar el acceso a hosts, repositorios, perfiles y bases de datos de SnapManager.

*Acerca de esta tarea*

Si ha configurado las credenciales con el comando set de credenciales, SnapManager no le solicita una contrase침a.

Es posible configurar credenciales de usuario al instalar SnapManager o una versi칩n posterior.

.Paso
. Introduzca el siguiente comando:
+
`*smsap credential set -repository -dbname _repo_service_name_ -host _repo_host_ -login -username _repo_username_ [-password _repo_password_] -port _repo_port_*`


