---
permalink: unix-administration/task-update-profiles.html 
sidebar: sidebar 
keywords: update, profile, modify, password, database, operating, system, os, authentication, updating, information, host, database, oracle, updating 
summary: 'Puede actualizar los perfiles para modificar la contraseña del perfil, la cantidad de backups que se deben retener, el acceso a la base de datos, la autenticación del sistema operativo (SO) con la autenticación de la base de datos y viceversa, e información sobre el host. Si cambia la información de contraseña de la base de datos Oracle, también debe cambiar esa información en el perfil.' 
---
= Actualizar perfiles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede actualizar los perfiles para modificar la contraseña del perfil, la cantidad de backups que se deben retener, el acceso a la base de datos, la autenticación del sistema operativo (SO) con la autenticación de la base de datos y viceversa, e información sobre el host. Si cambia la información de contraseña de la base de datos Oracle, también debe cambiar esa información en el perfil.

*Acerca de esta tarea*

Si la política de protección está habilitada en el perfil, no podrá cambiar la política mediante SnapManager. El administrador de almacenamiento debe cambiar la política mediante la consola de Protection Manager.

SnapManager (3.2 o posterior) permite actualizar el perfil para separar los backups de registros de archivos de los backups de archivos de datos mediante el `-separate-archivelog-backups` opción. Es posible especificar una duración de retención y una política de protección separadas para el backup de registros de archivos. SnapManager le permite incluir el backup de registros de archivos junto con el backup de base de datos en línea. También puede crear un backup de archivo de datos en línea y un backup de registro de archivo juntos para clonar. Cuando se crea un backup de archivos de datos en línea, los backups de registros de archivos se crean inmediatamente junto con los archivos de datos.

.Pasos
. Introduzca el siguiente comando:
+
`*smsap profile update -profile _profile_ [-new-profile _new_profile_name_] [-profile-password _profile_password_][-database-dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login -username _db_username_ -password _db_password_ -port _db_port_][-asminstance -asmusername _asminstance_username_ -asmpassword _asminstance_password_]] [{-rman{-controlfile | {-login  -username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_}}} | -remove-rman]-osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname -pattern _pattern_][[-protect [-protection-policy _policy_name_]]| [[-noprotect]] [-summary-notification] [-notification [-success-email _email_address1, email_address2_ -subject _subject_pattern_] [-failure-email _email_address1, email_address2_ -subject _subject_pattern_]] [-separate-archivelog-backups-retain-archivelog-backups-hours _hours_ | -days _days_ | -weeks _weeks_| -months _months_ [-protect [-protection-policy _policy_name_] | -noprotect] [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`

+
Las demás opciones para este comando son las siguientes:

+
``[-force] [-noprompt]``

+
``[-quiet | verbose]``

+
[cols="2a,4a"]
|===
| Si desea... | Realice lo siguiente... 


 a| 
*Cambie el perfil para utilizar la autenticación del sistema operativo*
 a| 
En lugar de agregar el nombre de usuario, la contraseña y el puerto, especifique lo siguiente:

** `-osaccount _account_name_` como nombre de la cuenta del sistema operativo
** `-osgroup _osgroup_` Como grupo asociado a la cuenta del sistema operativo, normalmente la cuenta utilizada para instalar Oracle




 a| 
*Utilice la autenticación de instancia de Automatic Storage Management (ASM) para crear el perfil*
 a| 
Especifique las credenciales para la autenticación de instancias de ASM.

** `-asmusername _asminstance_username_` Es el nombre de usuario utilizado para iniciar sesión en la instancia de ASM.
** `-asmpassword _asminstance_password_` Es la contraseña que se utiliza para iniciar sesión en la instancia de ASM.




 a| 
*Utilice un catálogo como repositorio de Oracle Recovery Manager (RMAN) o elimine RMAN*
 a| 
Especifique las siguientes opciones y variables:

** `-tnsname _tnsname_` como el nombre de tnsname definido en `tnsnames.ora` archivo.
** `-login -username _username_` Como nombre de usuario requerido para conectarse al catálogo de RMAN.
+
Si no se especifica, SnapManager utiliza la información de autenticación del sistema operativo. No se puede utilizar la autenticación del sistema operativo con bases de datos de Real Application Clusters (RAC).

** `-password _password_` Como contraseña de RMAN necesaria para conectarse al catálogo de RMAN.
** `-controlfile` Si utiliza el archivo de control como repositorio de RMAN.
** `-remove-rman` Para quitar RMAN.




 a| 
*Cambiar la política de retención de copias de seguridad para copias de seguridad de la base de datos en el perfil*
 a| 
Especifique el recuento de retención o la duración de la retención para una clase de retención, o ambos, para cambiar la política de retención. La duración se encuentra en unidades de la clase (por ejemplo, horas por hora, días por día).

** `-hourly` es la clase de retención por hora, para la cual `[-count _n_] [-duration _m_]]` son el recuento de retención y la duración de la retención, respectivamente.
** `-daily` es la clase de retención diaria, para la cual `[-count _n_] [-duration _m_]]` son el recuento de retención y la duración de la retención, respectivamente.
** `-weekly` es la clase de retención semanal, para la cual `[-count _n_] [-duration _m_]]` son el recuento de retención y la duración de la retención, respectivamente.
** `-monthly` es la clase de retención mensual, para la cual `[-count _n_] [-duration _m_]]` son el recuento de retención y la duración de la retención, respectivamente.




 a| 
*Desactive la protección de copia de seguridad para el perfil*
 a| 
Especifique `-noprotect` para no proteger los backups de la base de datos creados con el perfil. Para un perfil que tenga `-protect` activado, si desea deshabilitar la protección, se mostrará un mensaje de advertencia que indica que esta acción eliminará el conjunto de datos y no podrá restaurar o clonar backups para este perfil.



 a| 
*Activar notificaciones por correo electrónico para el estado de finalización de las operaciones de la base de datos*
 a| 
Especifique las siguientes opciones y variables:

** `-summary-notification` permite configurar una notificación por correo electrónico de resumen para varios perfiles en una base de datos de repositorio.
** `-notification` permite recibir una notificación por correo electrónico sobre el estado de finalización de la operación de la base de datos de un perfil.
** `-success -email _email_address2_` permite recibir una notificación por correo electrónico tras la finalización de una operación de base de datos correcta mediante un perfil nuevo o existente.
** `-failure -email _email_address2_` permite recibir una notificación por correo electrónico en una operación de base de datos fallida realizada mediante un perfil nuevo o existente.
** `-subject _subject_text_` especifica el texto del asunto para la notificación por correo electrónico al crear un perfil nuevo o un perfil existente. Si los ajustes de notificación no están configurados para el repositorio y intenta configurar las notificaciones de perfil o resumen mediante la interfaz de línea de comandos (CLI), se registra el siguiente mensaje en el registro de consola: `SMSAP-14577: Notification Settings not configured`.
+
Si configuró los ajustes de notificación e intenta configurar las notificaciones de resumen mediante la CLI sin habilitar la notificación de resumen para el repositorio, se registra el siguiente mensaje en el registro de consola: `SMSAP-14575: Summary notification configuration not available for this repository`





 a| 
*Actualice el perfil para crear una copia de seguridad de los archivos de registro de archivos por separado*
 a| 
Especifique las siguientes opciones y variables:

** `-separate-archivelog-backups` permite crear un backup de los archivos de registro de archivos independientemente de los archivos de la base de datos.
+
Después de especificar esta opción, puede crear una copia de seguridad sólo de archivos de datos o una copia de seguridad sólo de archivvelogs. No es posible crear un backup completo. Además, no puede revertir la configuración del perfil separando la copia de seguridad. SnapManager conserva los backups según la política de retención de los backups que se crearon antes de usar un backup de solo archivado.

** `-retain-archivelog-backups` establece la duración de la retención para los backups de registros de archivo.
+

NOTE: Si actualiza el perfil por primera vez, es posible separar los backups del registro de archivos de los archivos de datos mediante el `-separate-archivelog-backups` opción; debe proporcionar la duración de la retención de los backups de registros de archivos mediante la `-retain-archivelog-backups` opción. La configuración de la duración de la retención es opcional cuando se actualiza el perfil más adelante.

** `-protect` Crea un conjunto de datos de la aplicación en el servidor de Data Fabric Manager (DFM) y añade miembros relacionados con la base de datos, los archivos de datos, los archivos de control y los registros de archivos.
+
Si el conjunto de datos existe, se vuelve a utilizar cuando se crea un perfil.

** `-protection-policy` establece la política de protección en los backups de registros de archivo.
** `-include-with-online-backups` especifica que el backup de registros de archivo se incluya junto con el backup de la base de datos.
** `-no-include-with-online-backups` especifica que el backup del archivo de registro de archivos no se incluye junto con el backup de base de datos.




 a| 
*Cambiar el nombre de host de la base de datos de destino*
 a| 
Especifique `-host _new_db_host_` para cambiar el nombre de host del perfil.



 a| 
*Recopilar los archivos de volcado después de la operación de actualización de perfil*
 a| 
Especifique el `-dump` opción.

|===
. Para ver el perfil actualizado, escriba el comando siguiente: `smsap profile show`

