---
permalink: unix-administration/task-view-a-list-of-operations.html 
sidebar: sidebar 
keywords: view, summary, list, operation, perform, profile 
summary: Es posible ver una lista con un resumen de todas las operaciones realizadas en un perfil. 
---
= Ver una lista de operaciones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible ver una lista con un resumen de todas las operaciones realizadas en un perfil.

*Acerca de esta tarea*

Puede ver la siguiente información cuando enumere operaciones asociadas a un perfil en particular:

* Fecha de inicio y finalización cuando se ejecutó la operación
* Estado de la operación
* ID de la operación
* Tipo de operación
* Host en el que se ejecutó


.Paso
. Para enumerar la información resumida de todas las operaciones, utilice el siguiente comando:
+
`*smsap operation list profile -profile _profile_name_ -delimiter _character_ [-quiet | -verbose]*`

+
Cuando se especifica la opción -delimitador, el comando enumera cada fila en una línea separada y los atributos de esa fila están separados por el carácter especificado.


