---
permalink: unix-administration/task-configure-snapdrive-when-rbac-is-enabled.html 
sidebar: sidebar 
keywords: role-based, access, control, rbac, enable, configure, datafabric, manager, server, capability, capabilities, snapdrive, create, storage, system, regiser, configure, configuring 
summary: 'Cuando se habilita el control de acceso basado en roles (RBAC), debe configurar DataFabric Manager Server para que incluya las funcionalidades de RBAC. También debe registrar al usuario de SnapDrive creado en DataFabric Manager Server y al usuario raíz del sistema de almacenamiento en SnapDrive.' 
---
= Configure DataFabric Manager Server y SnapDrive cuando el control de acceso basado en roles está habilitado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se habilita el control de acceso basado en roles (RBAC), debe configurar DataFabric Manager Server para que incluya las funcionalidades de RBAC. También debe registrar al usuario de SnapDrive creado en DataFabric Manager Server y al usuario raíz del sistema de almacenamiento en SnapDrive.

.Pasos
. Configure DataFabric Manager Server.
+
.. Para actualizar DataFabric Manager Server para actualizar los cambios realizados directamente en el sistema de almacenamiento mediante la base de datos de destino, introduzca el siguiente comando:
+
`*dfm host discover _storage_system_*`

.. Cree un usuario nuevo en DataFabric Manager Server y defina la contraseña.
.. Para añadir un usuario del sistema operativo a la lista de administración del servidor de DataFabric Manager, escriba el siguiente comando:
+
`*dfm user add _sd-admin_*`

.. Para crear una función nueva en DataFabric Manager Server, introduzca el siguiente comando:
+
`*dfm role create _sd-admin-role_*`

.. Para agregar la funcionalidad DFM.Core.AccessCheck Global a la función, escriba el siguiente comando:
+
`*dfm role add _sd-admin-role_ DFM.Core.AccessCheck Global*`

.. Para añadir `sd-admin-role` para el usuario del sistema operativo, introduzca el siguiente comando:
+
`*dfm user role set _sd-adminsd-admin-role_*`

.. Para crear otra función en DataFabric Manager Server para el usuario raíz de SnapDrive, escriba el siguiente comando:
+
`*dfm role create _sd-protect_*`

.. Para añadir funcionalidades de RBAC al rol creado para el usuario raíz de SnapDrive o el administrador, escriba los siguientes comandos:
+
`*dfm role add _sd-protect_ SD.Config.Read Global*`

+
`*dfm role add _sd-protect_ SD.Config.Write Global*`

+
`*dfm role add _sd-protect_ SD.Config.Delete Global*`

+
`*dfm role add _sd-protect_ SD.Storage.Read Global*`

+
`*dfm role add _sd-protect_ DFM.Database.Write Global*`

+
`*dfm role add _sd-protect_ GlobalDataProtection*`

.. Para añadir el usuario de oracle de la base de datos de destino a la lista de administradores del servidor DataFabric Manager y asignar el rol sd-Protect, introduzca el siguiente comando:
+
`*dfm user add -r _sd-protecttardb_host1_\oracle*`

.. Para añadir el sistema de almacenamiento utilizado por la base de datos de destino en DataFabric Manager Server, escriba el siguiente comando:
+
`*dfm host set _storage_system_ hostLogin=oracle hostPassword=_password_*`

.. Para crear una función nueva en el sistema de almacenamiento utilizado por la base de datos de destino en DataFabric Manager Server, introduzca el siguiente comando:
+
`*dfm host role create -h _storage_system-c_ "api-**,login-*" _storage-rbac-role_**`

.. Para crear un grupo nuevo en el sistema de almacenamiento y asignar el nuevo rol creado en DataFabric Manager Server, introduzca el siguiente comando:
+
`*dfm host usergroup create -h _storage_system_-r _storage-rbac-rolestorage-rbac-group_*`

.. Para crear un nuevo usuario en el sistema de almacenamiento y asignar la nueva función y el grupo creado en DataFabric Manager Server, introduzca el siguiente comando:
+
`*dfm host user create -h _storage_system_-r _storage-rbac-role_ -p _password_ -g _storage-rbac-grouptardb_host1_*`



. Configure SnapDrive.
+
.. Para registrar las credenciales de `_sd-admin_` Usuario con SnapDrive, introduzca el comando siguiente:
+
`*snapdrive config set -dfm _sd-admindfm_host_*`

.. Para registrar el usuario raíz o el administrador del sistema de almacenamiento en SnapDrive, escriba el siguiente comando:
+
`*snapdrive config set _tardb_host1storage_system_*`




