---
permalink: unix-administration/task-reset-profile-password.html 
sidebar: sidebar 
keywords: reset, profile, password, remember, provide 
summary: Puede restablecer la contraseña del perfil si no recuerda la contraseña que ha proporcionado al crear el perfil. 
---
= Restablecer la contraseña del perfil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede restablecer la contraseña del perfil si no recuerda la contraseña que ha proporcionado al crear el perfil.

*Lo que necesitará*

* Debe asegurarse de que el servidor SnapManager esté en ejecución en la base de datos del repositorio.
* Debe tener las credenciales de usuario raíz del host en el que reside la base de datos del repositorio.
* Debe asegurarse de que el perfil no esté en uso para ninguna operación cuando se restablezca la contraseña para ese perfil.


*Acerca de esta tarea*

Puede restablecer la contraseña desde la interfaz de línea de comandos o desde la interfaz gráfica de usuario de SnapManager. Al restablecer la contraseña, SnapManager consulta al servidor SnapManager en el host de repositorios para identificar el sistema operativo para el host de repositorios. Debe introducir las credenciales de usuario autorizado para conectarse con el host de repositorios. El servidor SnapManager autentica a los usuarios con sus credenciales de raíz en la base de datos de repositorios. Cuando la autenticación se realiza correctamente, SnapManager restablece la contraseña del perfil en el servidor SnapManager con la nueva contraseña.


NOTE: SnapManager no mantiene el historial de las operaciones de restablecimiento de contraseña.

.Paso
. Restablezca la contraseña del perfil. Para ello, introduzca el siguiente comando:
+
`*smsap password reset -profile _profile_ [-profile-password _profile_password_] [-repository-hostadmin-password _admin_password_]*`


