---
permalink: unix-administration/task-update-target-database-hostname-associated-with-a-profile.html 
sidebar: sidebar 
keywords: snapmanager, sap, ability, update, host, name, target, database, profile 
summary: 'SnapManager (3.2 o posterior) para SAP permite actualizar el nombre de host de la base de datos de destino en el perfil de SnapManager.' 
---
= Actualice el nombre de host de la base de datos de destino asociado a un perfil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager (3.2 o posterior) para SAP permite actualizar el nombre de host de la base de datos de destino en el perfil de SnapManager.

*Lo que necesitará*

* El directorio inicial del usuario local debe tener en cuenta las asignaciones de perfil a repositorio.
* Se deben cerrar las sesiones de la interfaz gráfica de usuario (GUI) de SnapManager.
* En un entorno RAC, los clones o backups montados disponibles en el host especificado en el perfil deben eliminarse y desmontarse.


*Acerca de esta tarea*

Puede actualizar el perfil con el nuevo nombre de host únicamente mediante la CLI.

*Escenarios no admitidos para cambiar el nombre de host de la base de datos de destino en Profile*

Las siguientes situaciones no son compatibles para cambiar el nombre de host de la base de datos de destino en el perfil:

* Cambiar el nombre de host de la base de datos de destino mediante la interfaz gráfica de usuario de SnapManager
* Reversión de la base de datos del repositorio después de actualizar el nombre de host de la base de datos de destino del perfil
* Actualizar varios perfiles para un nuevo nombre de host de base de datos de destino ejecutando un solo comando
* Cambiar el nombre de host de la base de datos de destino cuando se ejecuta cualquier operación de SnapManager
* Cambiar el nombre de host de la base de datos de destino si SnapManager se instala en Solaris y si los números de unidad lógica de base de datos (LUN) se crean mediante el sistema de archivos montado en host con la pila de SVM.



NOTE: Después de actualizar el nombre de host de la base de datos de destino en el perfil, solo se cambia el nombre de host de la base de datos de destino. Se conservan todos los demás parámetros de configuración establecidos en el perfil.

Después de actualizar el nuevo nombre de host de la base de datos de destino en un perfil habilitado para la protección, se conservan el mismo conjunto de datos y las mismas políticas de protección para el perfil actualizado.

Después de cambiar el nombre de host del host objetivo, debe asegurarse de actualizar el nombre de host para todos los perfiles protegidos existentes antes de crear los nuevos perfiles protegidos. Para actualizar el nombre de host de un perfil, ejecute el `smsap profile update` comando.

Después de actualizar el nombre de host de la base de datos de destino, no se puede omitir o dividir el clon o desmontar el backup si el clon o el backup montado no están disponibles en el nuevo host. En tales situaciones, ejecutar las operaciones de SnapManager desde el host nuevo conlleva el fallo y las entradas obsoletas del host anterior. Para realizar operaciones de SnapManager, debe revertir al nombre de host anterior mediante el uso `profile update`.

. Introduzca el siguiente comando:
+
`*smsap profile update -profile _profile_ [-profile-password _profile_password_][-database-dbname _db_dbname_ -host _db_host_ [-sid _db_sid_] [-login-username _db_username_ -password _db_password_ -port _db_port_]] [{-rman{-controlfile | {-login-username _rman_username_ -password _rman_password_ -tnsname _rman_tnsname_}}} | -remove-rman]-osaccount _osaccount_ -osgroup _osgroup_ [-retain [-hourly [-count _n_] [-duration _m_]] [-daily [-count _n_] [-duration _m_]] [-weekly [-count _n_] [-duration _m_]] [-monthly [-count _n_] [-duration _m_]]] [-comment _comment_][-snapname-pattern _pattern_][[-protect [-protection-policy _policy_name_]]| [[-noprotect]] [-summary-notification] [-notification [-success -email _email_address1, email_address2_ -subject _subject_pattern_] [-failure -email _email_address1, email_address2_ -subject _subject_pattern_]] [-separate-archivelog-backups-retain-archivelog-backups -hours _hours_ | -days _days_ | -weeks _weeks_ | -months _months_ [-protect [-protection-policy _policy_name_] | -noprotect] [-include-with-online-backups | -no-include-with-online-backups]] [-dump]*`

+
Las demás opciones para este comando son las siguientes:

+
``[-force] [-noprompt]``

+
``[-quiet | -verbose]``

+
[cols="1a,2a"]
|===
| Si desea... | Realice lo siguiente... 


 a| 
*Cambiar el nombre de host de la base de datos de destino*
 a| 
`Specify -host _new_db_host_`

|===
. Para ver el nombre de host de la base de datos de destino del perfil, escriba el siguiente comando:
+
`*smsap profile show*`


