---
permalink: unix-administration/task-preview-backup-restore-information.html 
sidebar: sidebar 
keywords: preview, information, backup, restore, process, snapmanager, sap, successful 
summary: Puede obtener una vista previa de la información sobre un proceso de restauración de backup antes de que se produzca para ver información sobre la idoneidad para la restauración que SnapManager para SAP encuentra en el backup. SnapManager analiza los datos del backup para determinar si el proceso de restauración puede completarse correctamente. 
---
= Obtener una vista previa de la información de restauración de copia
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede obtener una vista previa de la información sobre un proceso de restauración de backup antes de que se produzca para ver información sobre la idoneidad para la restauración que SnapManager para SAP encuentra en el backup. SnapManager analiza los datos del backup para determinar si el proceso de restauración puede completarse correctamente.

*Acerca de esta tarea*

La vista previa de la restauración proporciona la siguiente información:

* Qué mecanismo de restauración (restauración rápida, restauración de sistema de archivos en el lado del almacenamiento, restauración de archivos en el lado del almacenamiento o restauración de copias de archivos del lado del host) se puede utilizar para restaurar cada archivo.
* Por qué no se utilizaron mecanismos más eficientes para restaurar cada archivo, al especificar el `-verbose` opción.


Si especifica el `-preview` en la `backup restore` SnapManager no restaura nada, pero enumera los archivos que se van a restaurar e indica cómo se restaurarán.


NOTE: Puede obtener una vista previa de todos los tipos de mecanismos de restauración. La vista previa muestra información acerca de un máximo de 20 archivos.

.Pasos
. Introduzca el siguiente comando:
+
`*smsap backup restore -profile _profile_name_ -label _label_ -complete -preview -verbose*`

+
*ejemplo*

+
Por ejemplo, introduzca:

+
[listing]
----
smsap backup restore -profile targetdb1_prof1
      -label full_bkup_sales_nov_08  -complete -preview -verbose
----
+
En el siguiente ejemplo, se muestran algunos archivos que se restauran con el proceso de restauración de copias de archivos del lado del host, además de explicar por qué algunos archivos no se pueden restaurar con la opción de restauración rápida. Si especifica el `-verbose` SnapManager muestra una sección de vista previa y una sección de análisis para explicar por qué no se puede restaurar cada archivo mediante el proceso de restauración rápida.

+
[listing]
----
PREVIEW:
The following files will be restored via host side file copy restore:
+DG2/sid/datafile10.dbf
+DG2/sid/datafile11.dbf

ANALYSIS:
The following reasons prevent certain files from being restored via fast restore:
Reasons:
 Newer snapshots of /vol/volume2 have volume clones: SNAP_1
*Newer backups will be freed: nightly2, nightly3
Files to Restore:
/mnt/systemB/volume2/system.dbf
/mnt/systemB/volume2/users.dbf
/mnt/systemB/volume2/sysaux.dbf
/mnt/systemB/volume2/datafile04.dbf
/mnt/systemB/volume2/datafile05.dbf

The following reasons prevent certain files from being restored via fast restore:
Reasons:
* Newer snapshots of /vol/adm_disks will be lost: ADM_SNAP_5
* Luns present which were created after snapshot SNAP_0 was created: /vol/adm_disks/disk5.lun
* Files not part of the restore scope will be reverted in file system: +DG2

Files Not in Restore Scope: +DG2/someothersid/data01.dbf
+DG2/someothersid/data02.dbf
Files to Restore:
+DG2/sid/datafile08.dbf +DG2/sid/datafile09.dbf
+DG2/sid/datafile10.dbf +DG2/sid/datafile11.dbf

* Reasons denoted with an asterisk (*) are overridable.
----
. Revise los motivos por los que no pueden usarse otros procesos de restauración.
. Inicie la operación de restauración sin `-preview` si sólo se muestran los motivos que se pueden anular.
+
Aún puede anular comprobaciones no obligatorias.


