---
permalink: unix-administration/task-set-credentials-after-clearing-credential-cache.html 
sidebar: sidebar 
keywords: clear, cache, remove, store, user, credential, host, repository, repositories, profile, setting 
summary: Después de borrar la caché para quitar las credenciales de usuario almacenadas, puede configurar las credenciales para hosts, repositorios y perfiles. 
---
= Configure las credenciales después de borrar la caché de credenciales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de borrar la caché para quitar las credenciales de usuario almacenadas, puede configurar las credenciales para hosts, repositorios y perfiles.

*Acerca de esta tarea*

Debe asegurarse de establecer las mismas credenciales de usuario para el repositorio, el host del perfil y el perfil que había especificado anteriormente. Se crea un archivo de credenciales cifrado al configurar las credenciales de usuario.

El archivo de credenciales está ubicado en `/root/.netapp/smsap/3.3.0`.

Desde la interfaz gráfica de usuario (GUI) de SnapManager, si no hay ningún repositorio en repositorios, realice los siguientes pasos:

.Pasos
. Haga clic en *tareas* > *Agregar repositorio existente* para agregar un repositorio existente.
. Ejecute los siguientes pasos para configurar las credenciales del repositorio:
+
.. Haga clic con el botón derecho del ratón en el repositorio y seleccione *Abrir*.
.. En la ventana *autenticación de credenciales de repositorio*, introduzca las credenciales de usuario.


. Realice los siguientes pasos para configurar las credenciales del host:
+
.. Haga clic con el botón derecho del ratón en el host bajo el repositorio y seleccione *Abrir*.
.. En la ventana *autenticación de credenciales de host*, introduzca las credenciales de usuario.


. Realice los siguientes pasos para configurar las credenciales del perfil:
+
.. Haga clic con el botón derecho del ratón en el perfil bajo el host y seleccione *Abrir*.
.. En la ventana *autenticación de credenciales de perfil*, introduzca las credenciales de usuario.



