---
permalink: unix-administration/task-clone-a-database-to-an-alternate-host.html 
sidebar: sidebar 
keywords: clone, create, command, database, alternate, host, cloning 
summary: Puede utilizar el comando clone create para clonar un backup de base de datos en un host alternativo. 
---
= Clonar una base de datos en un host alternativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el `clone create` comando para clonar un backup de base de datos en un host alternativo.

*Lo que necesitar치*

* Cree un perfil o tenga un perfil existente.
* Crear una copia de seguridad completa o tener una copia de seguridad de la base de datos existente.
* Cree una especificaci칩n de clon o tenga una especificaci칩n de clon existente.


.Paso
. Para clonar una base de datos en un host alternativo, introduzca el siguiente comando:
+
`*smsap clone create -backup-label _backup_label_name_ -newsid _new_sid_ -host _target_host_ -label _clone_label_ -comment _comment_text_ -profile _profile_name_ -clonespec _full_path_to_clonespecfile_*`

+
Oracle no permite ejecutar dos bases de datos con el mismo SID simult치neamente en el mismo host. Por este motivo, debe suministrar un SID nuevo para cada clon. Sin embargo, puede tener una base de datos en otro host con el mismo SID.


