---
permalink: unix-administration/task-configure-snapdrive-when-rbac-is-not-enabled.html 
sidebar: sidebar 
keywords: register, root, user, administrator, datafabric, manager, server, storage, system, snapdrive, data, protection, configuring, configure, rbac 
summary: Para habilitar la protección de datos, debe registrar en SnapDrive al usuario raíz o al administrador de DataFabric Manager Server y al usuario raíz del sistema de almacenamiento. 
---
= Configure SnapDrive cuando el control de acceso basado en roles no esté habilitado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para habilitar la protección de datos, debe registrar en SnapDrive al usuario raíz o al administrador de DataFabric Manager Server y al usuario raíz del sistema de almacenamiento.

.Pasos
. Para actualizar DataFabric Manager Server para actualizar los cambios realizados directamente en el sistema de almacenamiento mediante la base de datos de destino, introduzca el siguiente comando:
+
*ejemplo*

+
`*dfm host discover _storage_system_*`

. Para registrar el usuario raíz o el administrador de DataFabric Manager Server en SnapDrive, introduzca el siguiente comando:
+
*ejemplo*

+
`*snapdrive config set -dfm _Administratordfm_host_*`

. Para registrar el usuario raíz o el administrador del sistema de almacenamiento con SnapDrive, escriba el siguiente comando:
+
*ejemplo*

+
`*snapdrive config set root _storage_system_*`


