---
permalink: unix-administration/task-set-role-based-access-control-capabilities-and-roles.html 
sidebar: sidebar 
keywords: enable, role-based, access, control, rbac, snapmanager, snapdrive, capabilities, capability, setting, role, operation 
summary: 'Después de habilitar el control de acceso basado en roles (RBAC) para SnapManager mediante SnapDrive, es posible añadir funcionalidades de RBAC y usuarios a roles para ejecutar operaciones de SnapManager.' 
---
= Defina funciones y funcionalidades de control de acceso basado en roles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de habilitar el control de acceso basado en roles (RBAC) para SnapManager mediante SnapDrive, es posible añadir funcionalidades de RBAC y usuarios a roles para ejecutar operaciones de SnapManager.

*Lo que necesitará*

Debe crear un grupo en el servidor de Data Fabric Manager y añadir el grupo a los sistemas de almacenamiento primario y secundario. Ejecute los siguientes comandos:

* `dfm group create _smsap_grp_`
* `dfm group add _smsap_grpprimary_storage_system_`
* `dfm group add _smsap_grpsecondary_storage_system_`


*Acerca de esta tarea*

Es posible usar la interfaz web de Operations Manager o la interfaz de línea de comandos (CLI) del servidor de Data Fabric Manager para modificar las funcionalidades y los roles de RBAC.

En la tabla, se enumeran las capacidades de RBAC necesarias para ejecutar operaciones de SnapManager:

[cols="1a,2a,3a"]
|===
| Operaciones de SnapManager | Funcionalidades de RBAC necesarias cuando la protección de datos no está habilitada | Funcionalidades de RBAC necesarias cuando la protección de datos está habilitada 


 a| 
Creación de perfiles o actualización de perfiles
 a| 
SD.Storage.Read (smsap_grp)
 a| 
SD.Storage.Read (SMSAP `__profile_` conjunto de datos)



 a| 
Protección de perfiles
 a| 
DFM.Database.Write (smSAP_grp)

SD.Storage.Read (smsap_grp)

SD.Config.Read (smsap_grp)

SD.Config.Write (smsap_grp)

SD.Config.Delete (smsap_grp)

GlobalDataProtection
 a| 
Ninguno



 a| 
Crear backup
 a| 
SD.Storage.Read (smsap_grp)

SD.Snapshot.Write (smSAP_grp)

SD.Snapshot.Read (smSAP_grp)

SD.Snapshot.Delete (smsap_grp)
 a| 
SD.Storage.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Write (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Delete (SMSAP `__profile_` conjunto de datos)



 a| 
Creación de backup (con DBVerify)
 a| 
SD.Storage.Read (smsap_grp)

SD.Snapshot.Write (smSAP_grp)

SD.Snapshot.Read (smSAP_grp)

SD.Snapshot.Delete (smsap_grp)

SD.snapshot.Clone (smsap_grp)
 a| 
SD.Storage.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Write (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Delete (SMSAP `__profile_` conjunto de datos)

SD.snapshot.Clone (SMSAP `__profile_` conjunto de datos)



 a| 
Crear copia de seguridad (con RMAN)
 a| 
SD.Storage.Read (smsap_grp)

SD.Snapshot.Write (smSAP_grp)

SD.Snapshot.Read (smSAP_grp)

SD.Snapshot.Delete (smsap_grp)

SD.snapshot.Clone (smsap_grp)
 a| 
SD.Storage.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Write (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Delete (SMSAP `__profile_` conjunto de datos)

SD.snapshot.Clone (SMSAP `__profile_` conjunto de datos)



 a| 
Restauración de backup
 a| 
SD.Storage.Read (smsap_grp)

SD.Snapshot.Write (smSAP_grp)

SD.Snapshot.Read (smSAP_grp)

SD.Snapshot.Delete (smsap_grp)

SD.snapshot.Clone (smsap_grp)

SD.Snapshot.Restore (smSAP_grp)
 a| 
SD.Storage.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Write (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Delete (SMSAP `__profile_` conjunto de datos)

SD.snapshot.Clone (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Restore (SMSAP `__profile_` conjunto de datos)



 a| 
Eliminación de copia de seguridad
 a| 
SD.Snapshot.Delete (smsap_grp)
 a| 
SD.Snapshot.Delete (SMSAP `__profile_` conjunto de datos)



 a| 
Verificación de backup
 a| 
SD.Storage.Read (smsap_grp)

SD.Snapshot.Read (smSAP_grp)

SD.Snapshot.Clone (smsap_grp)
 a| 
SD.Storage.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Clone (SMSAP `__profile_` conjunto de datos)



 a| 
Montaje de backup
 a| 
SD.Storage.Read (smsap_grp)

SD.Snapshot.Read (smSAP_grp)

SD.Snapshot.Clone (smsap_grp)
 a| 
SD.Storage.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Clone (SMSAP `__profile_` conjunto de datos)



 a| 
Desmontaje de backups
 a| 
SD.Snapshot.Clone (smsap_grp)
 a| 
SD.Snapshot.Clone (SMSAP `__profile_` conjunto de datos)



 a| 
Clone create
 a| 
SD.Storage.Read (smsap_grp)

SD.Snapshot.Read (smSAP_grp)

SD.snapshot.Clone (smsap_grp)
 a| 
SD.Storage.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Read (SMSAP `__profile_` conjunto de datos)

SD.snapshot.Clone (SMSAP `__profile_` conjunto de datos)



 a| 
Clonar eliminación
 a| 
SD.Snapshot.Clone (smsap_grp)
 a| 
SD.Snapshot.Clone (SMSAP `__profile_` conjunto de datos)



 a| 
División de clones
 a| 
SD.Storage.Read (smsap_grp)

SD.Snapshot.Read (smSAP_grp)

SD.snapshot.Clone (smsap_grp)

SD.Snapshot.Delete (smsap_grp)

SD.Storage.Write (smSAP_grp)
 a| 
SD.Storage.Read (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Read (SMSAP `__profile_` conjunto de datos)

SD.snapshot.Clone (SMSAP `__profile_` conjunto de datos)

SD.Snapshot.Delete (SMSAP `__profile_` conjunto de datos)

SD.Storage.Write (SMSAP `__profile_` conjunto de datos)

|===
Para obtener detalles sobre la definición de las funcionalidades de RBAC, consulte la _Guía de administración del gestor de operaciones de Unified Manager de OnCommand_.

.Pasos
. Acceda a la consola de Operations Manager.
. En el menú Configuración, seleccione *roles*.
. Seleccione un rol existente o cree uno nuevo.
. Para asignar operaciones a los recursos de almacenamiento de la base de datos, haga clic en *Agregar capacidades*.
. En la página Editar configuración de función, para guardar los cambios realizados en la función, haga clic en *Actualizar*.


*Información relacionada*

http://support.netapp.com/documentation/productsatoz/index.html["Guía de administración del gestor de operaciones de OnCommand Unified Manager"^]
