---
settings:
  name: SnapManager for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de SnapManager para SAP
    url: "/index.html"
  - title: Notas de la versión
    url: "/reference-releasenotes.html"
  - section: unix-installation-cmode
  - section: unix-installation-7mode
  - section: unix-administration
  - section: windows
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Información general del producto
      url: "/unix-installation-cmode/reference-smsap-isg-product-overview.html"
    - title: Notas de la versión
      url: reference-releasenotes.html
  - title: Administración
    links:
    - title: Configuración de SnapManager para UNIX
      url: "/unix-administration/concept-configuring-snapmanager-for-oraclesap.html"
    - title: Configuración de SnapManager para Windows
      url: "/windows/concept-configuring-snapmanager-for-oraclesap.html"
  - title: Instalación y configuración
    links:
    - title: Flujo de trabajo de puesta en marcha (7-Mode)
      url: "/unix-installation-7mode/reference-smsap-isg-deployment-workflow.html"
    - title: Flujo de trabajo de implementación (Cluster Mode)
      url: "/unix-installation-cmode/reference-smsap-isg-deployment-workflow.html"
  - title: Más recursos
    links:
    - title: Soporte de NetApp
      url: https://mysupport.netapp.com/site/global/dashboard
    - title: Comunidades de NetApp
      url: https://community.netapp.com/
