---
permalink: unix-installation-cmode/reference-trademark.html 
sidebar: sidebar 
keywords: trademark, information 
summary: Información de Marca comercial 
---
= Información de Marca comercial
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Active IQ, AltaVault, Arch Design, ASUP, AutoSupport, Campaign Express, Clustered Data ONTAP, Customer Fitness, Data ONTAP, DataMotion, Element, Fitness, Flash Accel, Flash Cache, Flash Pool, FlexCache, FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, Fueled by SolidFire, GetSuccessful, Helix Design, LockVault, Manage ONTAP, MetroCluster, MultiStore, NetApp, NetApp Insight, OnCommand, ONTAP, ONTAPI, RAID DP, RAID-TEC, SANscreen, SANshare, SANtricity, SecureShare, Simplicity, Simulate ONTAP, Snap Creator, SnapCenter, SnapCopy, SnapDrive, SnapIntegrator, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect SnapRestore, Snapshot, SnapValidator, SnapVault, SolidFire, SolidFire Helix, StorageGRID, SyncMirror, Tech OnTap, Unbound Cloud y WAFL y otros nombres son marcas comerciales o marcas comerciales registradas de NetApp, Inc., en los Estados Unidos y/o otros países. Todas las demás marcas o productos son marcas comerciales o marcas registradas de sus respectivos propietarios y deben tratarse como tales. Una lista actualizada de marcas comerciales de NetApp está disponible en la web.

http://www.netapp.com/us/legal/netapptmlist.aspx[]
