---
permalink: unix-installation-cmode/task-create-the-repository-database-instance.html 
sidebar: sidebar 
keywords: repository, database, instance, oracle, snapmanager, stand-alone, target, create 
summary: La instancia de la base de datos del repositorio es una base de datos de Oracle en la que se crea el repositorio de SnapManager. La instancia de la base de datos del repositorio debe ser una base de datos independiente y no puede ser la base de datos de destino. 
---
= Cree la instancia de la base de datos del repositorio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La instancia de la base de datos del repositorio es una base de datos de Oracle en la que se crea el repositorio de SnapManager. La instancia de la base de datos del repositorio debe ser una base de datos independiente y no puede ser la base de datos de destino.



== Lo que necesitará

Debe tener una base de datos de Oracle y una cuenta de usuario para acceder a la base de datos.

.Pasos
. Iniciar sesión en SQL *Plus: `sqlplus '/ as sysdba'`
. Crear un nuevo espacio de tabla para el repositorio de SnapManager: `*create tablespacetablespace_name datafile ′/u01/app/oracle/oradata/datafile/tablespace_name.dbf′ size 100M autoextend on;*`
+
`tablespace_name` es el nombre del tablespace.

. Compruebe el tamaño de bloque del tablespace: `*select tablespace_name, block_size from dba_tablespaces;*`
+
SnapManager requiere un tamaño de bloque mínimo de 4 K para el espacio de tabla.


